domain_groups : {
    "U_SCCM_ADMINS" : {
        "scope": "universal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=Asa,DC=research,DC=haas,DC=local",
        "members" : [
            "G_SCCM_ADMINS",
        ]
    },
    "G_SCCM_ADMINS" : {
        "scope": "global", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=Asa,DC=research,DC=haas,DC=local",
        "members" : [
            "research.haas.local\\rubeaz"
        ]
    },
    "L_SCCM_MANAGED" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=Asa,DC=research,DC=haas,DC=local",
        "members" : [ 
            "fenris$",
            "architect$",
#            "bran$",
            "rsc01$"
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
    "G_LAPS_READER" : {
        "scope": "global", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=Asa,DC=research,DC=haas,DC=local",
        "members" : []
    },
    "L_LAPS_READER" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=Asa,DC=research,DC=haas,DC=local",
        "members" : [
            "G_LAPS_READER"
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
    "G_GMSA_ICHI" : {
        "scope": "global", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=Asa,DC=research,DC=haas,DC=local",
        "members" : [
        ]
    },
    "L_GMSA_ICHI" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=Asa,DC=research,DC=haas,DC=local",
        "members" : [
            "G_GMSA_ICHI",
            "fenris$", # computer account must be in the group not in nested groups
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
    "L_LOCAL_ADMINS" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "CN=Users,DC=research,DC=haas,DC=local",
        "members" : [
            # sccm push account
            howler
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
    "L_LOCAL_ADMINS_FENRIS" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "CN=Users,DC=research,DC=haas,DC=local",
        "members" : [
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
    "L_LOCAL_ADMINS_ARCHITECT" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "CN=Users,DC=research,DC=haas,DC=local",
        "members" : ["RESEARCH\\FENRIS$"],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
}
    

