ansible_connection: ssh 
ansible_user: vagrant
ansible_password: vagrant
#ansible_python_interpreter: /usr/bin/python3


# ######################
# gen-locale vars
# ######################
locales_gen: ["en_US.UTF-8 UTF-8"]
  #locales_gen: ["en_US.UTF-8 UTF-8", "fr_FR.UTF-8 UTF-8"]
vconsole_content: "KEYMAP=fr-latin1"
locale_lang: en_US.UTF-8

# ######################
# time-sync vars
# ######################
tz_timezone: Europe/Paris
tz_ntp_servers: "0.fr.pool.ntp.org 1.fr.pool.ntp.org 2.fr.pool.ntp.org 3.fr.pool.ntp.org"

# ######################
# reflector vars
# ######################
reflector_protocols: 
  - https
reflector_countries:
  - France
  - Germany
reflector_numberof: 5
reflector_sort_method: rate

pacman_arch_packages: [
  "vim",
  "openssh"
]