domain_groups : {
    "U_SCCM_ADMINS" : {
        "scope": "universal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=Cybernetics,OU=Asa,DC=haas,DC=local",
        "members" : [
            "G_SCCM_ADMINS",
        ]
    },
    "G_SCCM_ADMINS" : {
        "scope": "global", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=Cybernetics,OU=Asa,DC=haas,DC=local",
        "members" : [
            "haas.local\\jubeaz"
        ]
    },
    "U_LAPS_READER" : {
        "scope": "universal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=Cybernetics,OU=Asa,DC=haas,DC=local",
        "members" : [
            "G_LAPS_READER",
        ]
    },
    "G_LAPS_READER" : {
        "scope": "global", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=Cybernetics,OU=Asa,DC=haas,DC=local",
        "members" : [
            "emoon",
        ]
    },
    "G_GMSA_ICHI" : {
        "scope": "global", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=Cybernetics,OU=Asa,DC=haas,DC=local",
        "members" : [
        ]
    },
    "L_LAPS_READER" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=Cybernetics,OU=Asa,DC=haas,DC=local",
        "members" : [
            "U_LAPS_READER"
        ]
    },
    "L_GMSA_ICHI" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=Cybernetics,OU=Asa,DC=haas,DC=local",
        "members" : [
            "G_GMSA_ICHI",
            "fenris$", # computer account must be in the group not in nested groups
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": ["weyland.local\\G_LAPS_READER"]
    },
    "L_LOCAL_ADMINS" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "CN=Users,DC=haas,DC=local",
        "members" : [
            # sccm push account
            howler
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
    "L_SCCM_MANAGED" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "CN=Users,DC=haas,DC=local",
        "members" : [ 
            "fenris$",
            "architect$",
            "bran$",
            "DC03$"
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    } 
}

#         "foreign_members": ["weyland.local\\G_LAPS_READER"]
