domain_ous: {
    "Asa"             : { "name": "Asa",            "path" : "DC=haas,DC=local"},
    "HQ"              : { "name": "HQ",             "path" : "DC=haas,DC=local"},
    "MirrorMorph"     : { "name": "MirrorMorph",    "path" : "DC=haas,DC=local"},
    "Seidr"           : { "name": "Seidr",          "path" : "DC=haas,DC=local"},
    "Sportsmetal"     : { "name": "Sportsmetal",    "path" : "DC=haas,DC=local"},
    "Black Ops"       : { "name": "Black Ops",      "path" : "OU=Asa,DC=haas,DC=local"},
    "BO_servers"      : { "name": "Servers",        "path" : "OU=Black Ops,OU=Asa,DC=haas,DC=local"},
    "BO_workstations" : { "name": "Workstations",   "path" : "OU=Black Ops,OU=Asa,DC=haas,DC=local"},
    "BO_services"     : { "name": "Services",       "path" : "OU=Black Ops,OU=Asa,DC=haas,DC=local"},
    "BO_groups"       : { "name": "Groups",         "path" : "OU=Black Ops,OU=Asa,DC=haas,DC=local"},
    "BO_users"        : { "name": "Users",          "path" : "OU=Black Ops,OU=Asa,DC=haas,DC=local"},
    "BO_admins"       : { "name": "Admins",         "path" : "OU=Black Ops,OU=Asa,DC=haas,DC=local"},
    "Grey Ops"        : { "name": "Grey Ops",       "path" : "OU=Asa,DC=haas,DC=local"},
    "GO_servers"      : { "name": "Servers",        "path" : "OU=Grey Ops,OU=Asa,DC=haas,DC=local"},
    "GO_workstations" : { "name": "Workstations",   "path" : "OU=Grey Ops,OU=Asa,DC=haas,DC=local"},
    "GO_services"     : { "name": "Services",       "path" : "OU=Grey Ops,OU=Asa,DC=haas,DC=local"},
    "GO_groups"       : { "name": "Groups",         "path" : "OU=Grey Ops,OU=Asa,DC=haas,DC=local"},
    "GO_users"        : { "name": "Users",          "path" : "OU=Grey Ops,OU=Asa,DC=haas,DC=local"},
    "GO_admins"       : { "name": "Admins",         "path" : "OU=Grey Ops,OU=Asa,DC=haas,DC=local"},
    "White Ops"       : { "name": "White Ops",      "path" : "OU=Asa,DC=haas,DC=local"},
    "WO_servers"      : { "name": "Servers",        "path" : "OU=White Ops,OU=Asa,DC=haas,DC=local"},
    "WO_workstations" : { "name": "Workstations",   "path" : "OU=White Ops,OU=Asa,DC=haas,DC=local"},
    "WO_services"     : { "name": "Services",       "path" : "OU=White Ops,OU=Asa,DC=haas,DC=local"},
    "WO_groups"       : { "name": "Groups",         "path" : "OU=White Ops,OU=Asa,DC=haas,DC=local"},
    "WO_users"        : { "name": "Users",          "path" : "OU=White Ops,OU=Asa,DC=haas,DC=local"},
    "WO_admins"       : { "name": "Admins",         "path" : "OU=White Ops,OU=Asa,DC=haas,DC=local"},
    "Cybernetics"     : { "name": "Cybernetics",    "path" : "OU=Asa,DC=haas,DC=local"},
    "C_servers"       : { "name": "Servers",        "path" : "OU=Cybernetics,OU=Asa,DC=haas,DC=local"},
    "C_workstations"  : { "name": "Workstations",   "path" : "OU=Cybernetics,OU=Asa,DC=haas,DC=local"},
    "C_services"      : { "name": "Services",       "path" : "OU=Cybernetics,OU=Asa,DC=haas,DC=local"},
    "C_groups"        : { "name": "Groups",         "path" : "OU=Cybernetics,OU=Asa,DC=haas,DC=local"},
    "C_users"         : { "name": "Users",          "path" : "OU=Cybernetics,OU=Asa,DC=haas,DC=local"},
    "C_admins"        : { "name": "Admins",         "path" : "OU=Cybernetics,OU=Asa,DC=haas,DC=local"}
}