domain_service_accounts: {
    "imcguire" : {
        "firstname"       : "Isabel",
        "surname"         : "McGuire",
        "password"        : "zazc9DN_KpftZAvn", 
        "city"            : "-",
        "description"     : "",
        "groups"          : [], # only built-in
        "path"            : "CN=Users,DC=haas,DC=local",
        "delegates"       : ["CN=emoon,CN=Users,DC=haas,DC=local"], # RBCD / must be DN msDS-AllowedToActOnBehalfOfOtherIdentity
        "delegation_type" : false, # "KCD", "KUD", false
        "constrained"     : ["cifs/ws01", "cifs/ws01.haas.local"], # KCD / SPN list / msDS-AllowedToDelegateTo
        "proto_transition": true,  # KCD default false
        "sensitive"       : false,  
        "spns"            : ["HTTP/archer.weyland.local","HTTP/archer"],
        "ADAC": {
            "AllowReversiblePasswordEncryption": true,
            "CannotChangePassword":              true,
            "PasswordNeverExpires":              true,
            "PasswordNotRequired":               true,
            "AccountNotDelegated":               true,
            "DoesNotRequirePreAuth":             true
        }
    },  
    "KCD_pt" : {
        "firstname"       : "KCD",
        "surname"         : "pt",
        "password"        : "zazc9DN_KpftZAvn", 
        "city"            : "-",
        "description"     : "",
        "groups"          : [], # only built-in
        "path"            : "CN=Users,DC=haas,DC=local",
        "delegates"       : ["CN=emoon,CN=Users,DC=haas,DC=local"], # RBCD / must be DN msDS-AllowedToActOnBehalfOfOtherIdentity
        "delegation_type" : "KCD", # "KCD", "KUD", false
        "constrained"     : ["cifs/ws01", "cifs/ws01.haas.local"], # KCD / SPN list / msDS-AllowedToDelegateTo
        "proto_transition": true,  # KCD default false
        "spns"            : ["KCDPT/archer.weyland.local","KCDPT/archer"]
    },  
    "KCD" : {
        "firstname"       : "KCD",
        "surname"         : "without",
        "password"        : "zazc9DN_KpftZAvn", 
        "city"            : "-",
        "description"     : "",
        "groups"          : [], # only built-in
        "path"            : "CN=Users,DC=haas,DC=local",
        "delegates"       : ["CN=emoon,CN=Users,DC=haas,DC=local"], # RBCD / must be DN msDS-AllowedToActOnBehalfOfOtherIdentity
        "delegation_type" : "KCD", # "KCD", "KUD", false
        "constrained"     : ["cifs/ws01", "cifs/ws01.haas.local"], # KCD / SPN list / msDS-AllowedToDelegateTo
        "proto_transition": false,  # KCD default false
        "sensitive"       : false,  
        "spns"            : ["KCD/archer.weyland.local","KCD/archer"]
    },  
    "KUD" : {
        "firstname"       : "KUD",
        "surname"         : "-",
        "password"        : "zazc9DN_KpftZAvn", 
        "city"            : "-",
        "description"     : "",
        "groups"          : [], # only built-in
        "path"            : "CN=Users,DC=haas,DC=local",
        "delegates"       : ["CN=emoon,CN=Users,DC=haas,DC=local"], # RBCD / must be DN msDS-AllowedToActOnBehalfOfOtherIdentity
        "delegation_type" : "KUD", # "KCD", "KUD", false
        "constrained"     : ["cifs/ws01", "cifs/ws01.haas.local"], # KCD / SPN list / msDS-AllowedToDelegateTo
        "proto_transition": true,  # KCD default false
        "sensitive"       : false,  
        "spns"            : ["KUD/archer.weyland.local","KUD/archer"]
    },
    "ichi": {
        "firstname"       : "sccm",
        "surname"         : "sql",
        "password"        : "9Zjpo_mwCMcpgfrE", 
        "city"            : "-",
        "description"     : "sql service",
        "groups"          : [], # only built-in
        "path"            : "CN=Users,DC=haas,DC=local",
        "delegates"       : [], # RBCD / must be DN msDS-AllowedToActOnBehalfOfOtherIdentity
        "delegation_type" : false, # "KCD", "KUD", false
        "constrained"     : ["cifs/ws01", "cifs/ws01.haas.local"], # KCD / SPN list / msDS-AllowedToDelegateTo
        #"proto_transition": true,  # KCD default false
        "sensitive"       : false,  
        "spns"            : ["MSSQLSvc/fenris.haas.lab:1433","MSSQLSvc/fenris.haas.lab"]
    },
    "drafter": {
        "firstname"       : "sccm",
        "surname"         : "sql local",
        "password"        : "9Zjpo_mwCMcpgfrE", 
        "city"            : "-",
        "description"     : "sql service",
        "groups"          : [], # only built-in
        "path"            : "CN=Users,DC=haas,DC=local",
        "delegates"       : [], # RBCD / must be DN msDS-AllowedToActOnBehalfOfOtherIdentity
        "delegation_type" : false, # "KCD", "KUD", false
        "constrained"     : ["cifs/ws01", "cifs/ws01.haas.local"], # KCD / SPN list / msDS-AllowedToDelegateTo
        #"proto_transition": true,  # KCD default false
        "sensitive"       : false,  
        "spns"            : ["MSSQLSvc/bran.haas.lab:1433","MSSQLSvc/bran.haas.lab"]
    }
}

domain_users_regular: {
    "emoon" : {
        "firstname"       : "Estelle",
        "surname"         : "Moon",
        "password"        : "Nps4ffWx7omDc5_h", 
        "city"            : "-",
        "description"     : "",
        "groups"          : [], # only built-in
        "path"            : "CN=Users,DC=haas,DC=local"
    },

    "mbellamy" : {
        "firstname"       : "Mason",
        "surname"         : "Bellamy",
        "password"        : "b_QNoDKoVJTjU3gq", 
        "city"            : "-",
        "description"     : "",
        "groups"          : ["Domain Admins"], # only built-in
        "path"            : "CN=Users,DC=haas,DC=local"
    },
    "mhendrik" : {
        "firstname"       : "Mr.",
        "surname"         : "Hendrik",
        "password"        : "b_QNoDKoVJTjU3gq", 
        "city"            : "-",
        "description"     : "DB link user",
        "groups"          : [], # only built-in
        "path"            : "CN=Users,DC=haas,DC=local"
    },
    "rknight" : {
        "firstname"       : "Ryon",
        "surname"         : "Knight",
        "password"        : "5jqkKJJjmqup_o_E", 
        "city"            : "-",
        "description"     : "DB admin",
        "groups"          : [], # only built-in
        "path"            : "CN=Users,DC=haas,DC=local"
    },
    "thaas" : {
        "firstname"       : "Thomas",
        "surname"         : "Haas",
        "password"        : "s_yrPbrqtHbc3n7a", 
        "city"            : "-",
        "description"     : "",
        "groups"          : [], # only built-in
        "path"            : "CN=Users,DC=haas,DC=local"
   },
    "lowpriv" : {
        "firstname"       : "low",
        "surname"         : "l",
        "password"        : "priv", 
        "city"            : "-",
        "description"     : "",
        "groups"          : [], # only built-in
        "path"            : "CN=Users,DC=haas,DC=local"
    },
    "jubeaz" : {
        "firstname"       : "Mr.",
        "surname"         : "Jubeaz",
        "password"        : "jubeaz", 
        "city"            : "-",
        "description"     : "",
        "groups"          : ["Domain Admins"], # only built-in
        "path"            : "CN=Users,DC=haas,DC=local"
    },
    "hagen" : {
        "firstname"       : "ice",
        "surname"         : "barrier",
        "password"        : "haGen_Pa$$word", 
        "city"            : "-",
        "description"     : "naa",
        "groups"          : [], # only built-in
        "path"            : "CN=Users,DC=haas,DC=local"
    },
    "howler" : {
        "firstname"       : "ice",
        "surname"         : "Trap",
        "password"        : "h0w1er_Pa$$word", 
        "city"            : "-",
        "description"     : "push_account",
        "groups"          : [], # only built-in
        "path"            : "CN=Users,DC=haas,DC=local"
    }
}