sccm_mssql_server: eli
sccm_site_code: 'HS1'
sccm_network_access_account: "hagen"
sccm_push_account: "howler"
sccm_clients: ['fenris', 'architect']
sccm_pxe_pass: "qKjhz__Qyd_YLTu4"
sccm_account_da: "mbellamy"
sccm_pxe_location: "LDAP://CN=Computers,DC=research,DC=haas,DC=local"
sccm_pxe_admin_pass: "NuvqREtyaT_k9E5C"
sccm_admins: ["HAAS\\U_SCCM_ADMINS"]
sccm_discovery_group: "U_SCCM_MANAGED"
