plbr_cert_templates: ["ESC1", "ESC2", "TLSServer"]
plbr_tls_server_certificate_template_name: "TLSServer"
plbr_ca_vulns: ["ESC6"]
plbr_web_enrollment: true # ESC8
plbr_ca_common_name: "internal-ca"

plbr_acls_adcs_templates: {
  # 'FullControl', 'Read', 'Write', 'Enroll', 'Autoenroll'.
  "F_L_CERT_MGR_esc1" : {"for": "L_CERT_MGR", "to": "ESC1", "right": "FullControl", "inheritance": "None"},
  "R_HaasComputers_TLSServer" : {"for": "HAAS\\Domain computers", "to": "TLSServer", "right": "Read", "inheritance": "None"},
  "E_HaasComputers_TLSServer" : {"for": "HAAS\\Domain computers", "to": "TLSServer", "right": "Enroll", "inheritance": "None"},
  "A_HaasComputers_TLSServer" : {"for": "HAAS\\Domain computers", "to": "TLSServer", "right": "Autoenroll", "inheritance": "None"},
  "R_ResearchComputers_TLSServer" : {"for": "RESEARCH\\Domain computers", "to": "TLSServer", "right": "Read", "inheritance": "None"},
  "E_ResearchComputers_TLSServer" : {"for": "RESEARCH\\Domain computers", "to": "TLSServer", "right": "Enroll", "inheritance": "None"},
  "A_ResearchComputers_TLSServer" : {"for": "RESEARCH\\Domain computers", "to": "TLSServer", "right": "Autoenroll", "inheritance": "None"}
}

plbr_acls_adcs_authority: {
  # 'ManageCA', 'ManageCertificates', 'Read', 'Enroll'
  "M_L_CERT_MGR_internal_ca" : {"for": "L_CERT_MGR", "to": "{{plbr_ca_common_name}}", "right": "ManageCertificates", "inheritance": "None"},
  "R_L_CERT_REQUESTER_internal_ca" : {"for": "L_CERT_REQUESTER", "to": "{{plbr_ca_common_name}}", "right": "Enroll", "inheritance": "None"},
  "E_L_CERT_REQUESTER_internal_ca" : {"for": "L_CERT_REQUESTER", "to": "{{plbr_ca_common_name}}", "right": "Read", "inheritance": "None"}
}