# plbr_enable_webdav: false
# 0: UAC won't prompt (like disabled)                                                                                                                                                                  │
# 1: ask for username and password to execute the binary with high rights (on Secure Desktop)                                                                                                          │
# 2: Always notify me ask for confirmation to the administrator when he tries to execute something with high privileges (on Secure Desktop)                                                            │
# 3: like 1 but not necessary on Secure Desktop                                                                                                                                                        │
# 4: like 2 but not necessary on Secure Desktop                                                                                                                                                        │
# 5: ask the administrator to confirm to run non Windows binaries with high privileges     
#plbr_uac_level: 5
#plbr_run_as_ppl: false,
#plbr_windows_defender: true

#plbr_firewall_profiles: {
#  "Domain": {"enabled": "False", "inbound": "allow", "outbound": "allow"},
#  "Public": {"enabled": "False", "inbound": "allow", "outbound": "allow"},
#  "Private": {"enabled": "False", "inbound": "allow", "outbound": "allow"},
#}


#plbr_firewall_rules: {
#   "FTP_IN_1": {
#      "name": "FTP In",
#      "enabled": true, 
#      "action": "allow", 
#      "profiles": ["Domain"], 
#      "direction": "inbound", # inbound, outbound
#      "localip": ["any"], 
#      "localport": [21],  
#      "protocol": "tcp", # any or value
#      "remoteip": ["any"],  
#      "remoteport": ["any"] 
#      #"group": "ansible" # default ansible
#    },
#   "mssql_default_instance": {
#      "name": "SQLServer default instance",
#      "enabled": true, 
#      "action": "allow", 
#      "profiles": ["Domain"], 
#      "direction": "inbound", # inbound, outbound
#      "localip": ["any"], 
#      "localport": [1433],  
#      "protocol": "tcp", # any or value
#      "remoteip": ["172.17.0.10", "172.17.0.20"],  
#      "remoteport": ["any"] 
#      #"group": "ansible" # default ansible
#    },
#   "mssql_browser_service": {
#      "name": "SQLServer browser service",
#      "enabled": true, 
#      "action": "allow", 
#      "profiles": ["Domain"], 
#      "direction": "inbound", # inbound, outbound
#      "localip": ["any"], 
#      "localport": [1433],  
#      "protocol": "udp", # any or value
#      "remoteip": ["172.17.0.10", "172.17.0.20"],  
#      "remoteport": ["any"] 
#      #"group": "ansible" # default ansible
#    }
#}
