local_groups: {
    "Administrators" : ["haas.local\\rknight", "HAAS\\mhendrik", "HAAS\\BRAN$", "HAAS\\ichi","haas.local\\L_LOCAL_ADMINS"]
#    "Remote Desktop Users" : [],
#    "Remote Management Users": []
}


local_users: {
    "LA_jubeaz" : {
        "password"        : "jubeaz", 
        "groups"          : ["Administrators"]
        }
}