#mssql_instance_name: "{{hostname}}"
mssql_sa_password: "ftrum_Ya5d7DCQQN"
#mssql_svcaccount_method: 'gmsa' # domain, gmsa, local
#mssql_svcaccount_key: "ichi" 
#mssql_svcaccount_method: 'local' # domain, gmsa, local
#mssql_svcaccount_key: "ichi" 
mssql_svcaccount_method: 'domain' # domain, gmsa, local
mssql_svcaccount_key: "ichi" # default : 'NT AUTHORITY\\NETWORK SERVICE'

mssql_sysadmins: ["HAAS\\mhendrik", "HAAS\\jubeaz", "HAAS\\administrator", "HAAS\\BRAN$", "HAAS\\ichi"]
mssql_executeaslogin: {
    "HAAS\\rknight" : "sa"
    }
mssql_executeasuser: {
    "master_dbo": {
        "user": "HAAS\\mhendrik",
        "db"  : "master",
        "impersonate" : "dbo"
        },
    "dbms_dbo": {
        "user": "HAAS\\mhendrik",
        "db"  : "msdb",
        "impersonate" : "dbo"
        }
    }
mssql_linked_servers: {
    "archer" : {
        "data_src": "archer.weyland.local",
        "users_mapping": [
            {"local_login": "HAAS\\mhendrik","remote_login": "WEYLAND\\anson", "remote_password": "z77w_TeCUCD_wLrD"}
            ]
        }
    }