plbr_local_users: {
    "LA_jubeaz" : {
        "password"        : "Zaebuj12345+-", 
        }
}

plbr_local_groups: {
    "Administrators" : [".\\LA_jubeaz", "HAAS\\L_LOCAL_ADMINS", "HAAS\\L_LOCAL_ADMINS_HYPOXIA"],
    "Remote Management Users": [".\\LA_jubeaz","HAAS\\L_LOCAL_ADMINS", "HAAS\\L_LOCAL_ADMINS_HYPOXIA", "HAAS\\lowpriv"],
    "Remote Desktop Users" : [".\\LA_jubeaz","HAAS\\L_LOCAL_ADMINS", "HAAS\\L_LOCAL_ADMINS_HYPOXIA", "HAAS\\lowpriv"]
}


# Get-WindowsCapability -Name RSAT* -Online | Select-Object -Property DisplayName, State
plbr_extra_features: [
    "Rsat.CertificateServices.Tools~~~~0.0.1.0",
    "Rsat.ActiveDirectory.DS-LDS.Tools~~~~0.0.1.0",
    "Rsat.Dns.Tools~~~~0.0.1.0",
    "Rsat.FileServices.Tools~~~~0.0.1.0",
    "Rsat.GroupPolicy.Management.Tools~~~~0.0.1.0",
    "Rsat.RemoteAccess.Management.Tools~~~~0.0.1.0",
    "Rsat.RemoteDesktop.Services.Tools~~~~0.0.1.0",
    "Rsat.ServerManager.Tools~~~~0.0.1.0",
    "Rsat.DHCP.Tools~~~~0.0.1.0"
]



#features: ["NET-Framework-Core"]
## https://community.chocolatey.org/packages
plbr_softwares: [  "git", "visualstudio2022community", "notepadplusplus", "python", "libreoffice","7zip"]

plbr_user_repos: {
    jubeaz: [
        ["Mimikatz", "https://github.com/gentilkiwi/mimikatz.git"],
        ["Rubeus", "https://github.com/GhostPack/Rubeus"],
        [HardeningKitty, https://github.com/scipag/HardeningKitty.git]
    ]
}

plbr_user_downloads: {
    jubeaz: [
        ["GRMWDK_EN_7600_1.ISO", "https://download.microsoft.com/download/4/A/2/4A25C7D5-EFBE-4182-B6A9-AE6850409A78/GRMWDK_EN_7600_1.ISO"]
    ]
}


