plbr_domain_groups : {
#########################
# LAPS
#########################
    "G_LAPS_READER" : {
        "scope": "global", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=HQ,DC=haas,DC=local",
        "members" : [
        ]
    },
    "L_LAPS_READER" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=HQ,DC=haas,DC=local",
        "members" : [
        ]
    },
#########################
# GMSA
#########################
#########################
# Local Admins
#########################
    "L_LOCAL_ADMINS" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "CN=Users,DC=haas,DC=local",
        "members" : [
            "HAAS\\howler",
            "HAAS\\waco"
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
    "L_LOCAL_ADMINS_ELI" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "CN=Users,DC=haas,DC=local",
        "members" : [
            "HAAS\\bran$",  # CFGMGR REQUIREMENTS ADIN OF MSSQL SERVER
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
    "L_LOCAL_ADMINS_BRAN" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "CN=Users,DC=haas,DC=local",
        "members" : [
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
    "L_LOCAL_ADMINS_PULSE" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "CN=Users,DC=haas,DC=local",
        "members" : [
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
#########################
# WAC
#########################
    "L_WAC_AADMIN" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "CN=Users,DC=haas,DC=local",
        "members" : [
            "HAAS\\waco"
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
    "L_WAC_USER" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "CN=Users,DC=haas,DC=local",
        "members" : [
            "HAAS\\waco"
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
#########################
# ADCS CA
#########################
    "G_CERT_MGR" : {
        "scope": "global", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=HQ,DC=haas,DC=local",
        "members" : [
        ]
    },
    "L_CERT_MGR" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=HQ,DC=haas,DC=local",
        "members" : [
            "G_CERT_MGR"
        ]
    },
    "L_CERT_REQUESTER" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=HQ,DC=haas,DC=local",
        "members" : [
            "U_CERT_TMPLT_MachineServerAuthentication"
        ]
    },
#########################
# ADCS Template
#########################
    "U_CERT_TMPLT_MachineServerAuthentication": {
        "scope": "universal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=HQ,DC=haas,DC=local",
        "members" : [
             "HAAS\\Domain Computers"
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": ["RESEARCH\\Domain Computers"]
    },
    "L_CERT_TMPLT_MachineServerAuthentication" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=HQ,DC=haas,DC=local",
        "members" : [
            "U_CERT_TMPLT_MachineServerAuthentication",
        ]
    },
#########################
# MSSQL
#########################
    "G_SYSADMIN_ELI" : {
        "scope": "global", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "CN=Users,DC=haas,DC=local",
        "members" : [
            "HAAS\\jubeaz", 
            "HAAS\\administrator", 
            "HAAS\\drafter",
            "HAAS\\bran$"  # CFGMGR REQUIREMENTS ADIN OF MSSQL SERVER
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
    "G_SQL_ACCOUNTS_ELI" : {
        "scope": "global", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "CN=Users,DC=haas,DC=local",
        "members" : [
            "G_SYSADMIN_ELI"
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
    "G_SYSADMIN_FENRIS" : {
        "scope": "global", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "CN=Users,DC=haas,DC=local",
        "members" : [
            "HAAS\\jubeaz"
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
    "G_SQL_ACCOUNTS_FENRIS" : {
        "scope": "global", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "CN=Users,DC=haas,DC=local",
        "members" : [
            "HAAS\\G_SYSADMIN_FENRIS"
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
#########################
# Configuration Manager
#########################
    "G_CFGMGR_ADMINS" : {
        "scope": "global", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=HQ,DC=haas,DC=local",
        "members" : [
            "HAAS\\hubeaz"
        ]
    },
    "U_CFGMGR_ADMINS" : {
        "scope": "universal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=HQ,DC=haas,DC=local",
        "members" : [
            "HAAS\\G_CFGMGR_ADMINS",
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": ["RESEARCH\\G_CFGMGR_ADMINS"]
    },
    "G_CFGMGR_MANAGED" : {
        "scope": "global", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=HQ,DC=haas,DC=local",
        "members" : [ 
            "bran$"
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
    "U_CFGMGR_MANAGED" : {
        "scope": "universal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=HQ,DC=haas,DC=local",
        "members" : [ 
            "HAAS\\G_CFGMGR_MANAGED",
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": ["RESEARCH\\G_CFGMGR_MANAGED"]
    },
#########################
# NPS
#########################
    "L_NPS_EAP_TLS" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=HQ,DC=haas,DC=local",
        "members" : [ 
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
    "L_NPS_PEAP_MSCHAPV2" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=HQ,DC=haas,DC=local",
        "members" : [ 
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
    "L_NPS_EAP_MSCHAPV2" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=HQ,DC=haas,DC=local",
        "members" : [ 
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
    "L_NPS_UNSECURE" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=HQ,DC=haas,DC=local",
        "members" : [ 
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
    "L_NPS_ALL" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=HQ,DC=haas,DC=local",
        "members" : [ 
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },


}

plbr_domain_builtin_groups: {
    "Enterprise Admins" : {
        "path" : "CN=Users,DC=haas,DC=local",
        "members" : [
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
    "Schema Admins" : {
        "path" : "CN=Users,DC=haas,DC=local",
        "members" : [
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
}