domain_groups : {
    "G_CERT_MGR" : {
        "scope": "global", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=HQ,DC=haas,DC=local",
        "members" : [
        ]
    },
    "L_CERT_MGR" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=HQ,DC=haas,DC=local",
        "members" : [
            "G_CERT_MGR"
        ]
    },
    "U_LAPS_READER" : {
        "scope": "universal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=HQ,DC=haas,DC=local",
        "members" : [
            "G_LAPS_READER",
        ]
    },
    "G_LAPS_READER" : {
        "scope": "global", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=HQ,DC=haas,DC=local",
        "members" : [
        ]
    },
    "L_LAPS_READER" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=HQ,DC=haas,DC=local",
        "members" : [
            "U_LAPS_READER"
        ]
    },
    "L_LOCAL_ADMINS" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "CN=Users,DC=haas,DC=local",
        "members" : [
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
    "L_LOCAL_ADMINS_BRAN" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "CN=Users,DC=haas,DC=local",
        "members" : [
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
}

#         "foreign_members": ["weyland.local\\G_LAPS_READER"]

domain_builtin_groups: {
    "Enterprise Admins" : {
        "path" : "CN=Users,DC=haas,DC=local",
        "members" : [
        ],
        "foreign_users": ["research.haas.local\\Administrator"],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
    "Schema Admins" : {
        "path" : "CN=Users,DC=haas,DC=local",
        "members" : [
        ],
        "foreign_users": ["research.haas.local\\Administrator"],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
}