
#domain_password : "Jubeaz12345+-"
plbr_domain_netbios_name: "HAAS"
plbr_domain_name : "haas.local"

plbr_trust_domain_dc_inventory_key : "dc_wld" # ansible inventory name
plbr_parent_domain_dc_inventory_key: "" # ansible inventory name
