mssql_instance_name: "{{hostname}}"
mssql_sa_password: "ftrum_Ya5d7DCQQN"
mssql_svcaccount_method: 'gmsa' # domain, gmsa, local
mssql_svcaccount_key: "ichi" 
#mssql_svcaccount_method: 'local' # domain, gmsa, local
#mssql_svcaccount_key: "ichi" 


mssql_sysadmins: ["HAAS\\mhendrik"]
mssql_executeaslogin: {
    "HAAS\\rknight" : "sa",
    "HAAS\\jubeaz" : "sa"
    }
mssql_executeasuser: {
    "master_dbo": {
        "user": "HAAS\\mhendrik",
        "db"  : "master",
        "impersonate" : "dbo"
        },
    "dbms_dbo": {
        "user": "HAAS\\mhendrik",
        "db"  : "msdb",
        "impersonate" : "dbo"
        }
    }
mssql_linked_servers: {
    "archer" : {
        "data_src": "archer.weyland.local",
        "users_mapping": [
            {"local_login": "HAAS\\mhendrik","remote_login": "WEYLAND\\anson", "remote_password": "z77w_TeCUCD_wLrD"}
            ]
        }
    }


#           "mssql":{
#               "sa_password": "Sup1_sa_P@ssw0rd!",
#               "svcaccount" : "sql_svc",
#               "sysadmins" : [
#                   "NORTH\\jon.snow"
#               ],
#               "executeaslogin" : {
#                   "NORTH\\samwell.tarly" : "sa",
#                   "NORTH\\brandon.stark" :  "NORTH\\jon.snow"
#               },
#               "executeasuser" : {
#                   "arya_master_dbo": {
#                       "user": "NORTH\\arya.stark",
#                       "db"  : "master",
#                       "impersonate" : "dbo"
#                   },
#                   "arya_dbms_dbo": {
#                       "user": "NORTH\\arya.stark",
#                       "db"  : "msdb",
#                       "impersonate" : "dbo"
#                   }
#               },
#               "linked_servers": {
#                   "BRAAVOS" : {
#                       "data_src": "braavos.essos.local",
#                       "users_mapping": [
#                           {"local_login": "NORTH\\jon.snow","remote_login": "sa", "remote_password": "sa_P@ssw0rd!Ess0s"}
#                       ]
#                   }
#               }
#           }