- name: "Harden DCs"
  hosts: dc_wld
  max_fail_percentage: 0
  roles:
    #- { role: 'windows_settings_hardeningkitty', tags: 'server'}
    - { role: 'windows_domain_gpo', tags: 'server'}
  vars:
    hardeningkitty_action: "play"
    