- name: BASTION BUILD
  hosts: wallix_bastion
  tags: mandatory
  gather_facts: false
  max_fail_percentage: 0
  tasks:
    - name: Get Bastion auth cookie
      ansible.builtin.include_role:
        name: wallix_bastion_auth
      vars:
        wallix_bastion_auth_url: "{{ bastion_url }}"
        wallix_bastion_auth_user: "{{ api_user }}"
        wallix_bastion_auth_password: "{{ api_password }}"

    - name: Create devices
      ansible.builtin.include_role:
        name: wallix_bastion_device
      vars:
        wallix_bastion_device_url: "{{ bastion_url }}"
        wallix_bastion_device_cookie: "{{ wallix_bastion_auth_cookie }}"
        wallix_bastion_device_devices: "{{ plbr_devices }}"

# create device service