---
- name: DOMAIN SET FACTS
  hosts: domain
  tags: mandatory
  gather_facts: false
  max_fail_percentage: 0
  tasks:
    - name: Register domain info on all domain computers
      ansible.builtin.set_fact:
        plbr_domain_dc_ip: "{{ hostvars[plbr_domain_dc_inventory_key].plbr_domain_ip }}"
        plbr_domain_dc_name: "{{ hostvars[plbr_domain_dc_inventory_key].plbr_hostname }}"
        plbr_domain_ldap_name: "DC={{ hostvars[plbr_domain_dc_inventory_key].plbr_domain_name.split('.') | join(',DC=') }}"
        cacheable: true

    - name: Register domain  info on non DC
      ansible.builtin.set_fact:
        plbr_domain_name: "{{ hostvars[plbr_domain_dc_inventory_key].plbr_domain_name }}"
        plbr_domain_password: "{{ hostvars[plbr_domain_dc_inventory_key].plbr_domain_password }}"
        plbr_domain_netbios_name: "{{ hostvars[plbr_domain_dc_inventory_key].plbr_domain_netbios_name }}"
        plbr_domain_gmsa: "{{ hostvars[plbr_domain_dc_inventory_key].plbr_domain_gmsa }}"
        plbr_domain_laps_path: "{{ hostvars[plbr_domain_dc_inventory_key].plbr_domain_laps_path }}"
        plbr_domain_path: "{{ hostvars[plbr_domain_dc_inventory_key].plbr_domain_real_computers[plbr_hostname].path }}"
        plbr_adcs_server_key: "{{ hostvars[plbr_domain_dc_inventory_key].plbr_adcs_server_key }}"
        cacheable: true
      when: inventory_hostname not in groups['dc']
