- name: BASTION SET FACTS
  hosts: wallix_bastion
  tags: mandatory
  gather_facts: false
  max_fail_percentage: 0
  tasks:
#    - name: Display hostvars in a readable format
#      ansible.builtin.debug:
#        var: hostvars['haas_srv01']
#    - name: STOP
#      ansible.builtin.fail:
#        msg: "STOP"
    - name: Register wallix bastion targets as a fact
      no_log: true
      ansible.builtin.set_fact:
        plbr_devices: |
          {{ plbr_devices | default([]) |
              combine({
                item.value.plbr_hostname: {
                   'ip': item.value.plbr_domain_ip,
                   'key': item.key,
                   'local_domain': item.value.plbr_wallix_bastion_local_domain,
                   'services': item.value.plbr_wallix_bastion_services
                }
              })
          }}
        cacheable: true
      when: "'haas_domain' in item.value.group_names"
      with_dict: "{{ hostvars }}"

#    - name: Display wallix bastion targets fact
#      ansible.builtin.debug:
#        var: plbr_devices

#    - name: Display hostvars in a readable format
#      ansible.builtin.debug:
#        var: hostvars['bastion']
