---
- name: BUILD ALL COMPUTERS
  hosts: domain
  max_fail_percentage: 0
  tags: 'build_computers'
  gather_facts: false
  tasks:
    - name: Disable Management Interface
      ansible.builtin.include_role:
        name: windows_cfg_manage_net_adapter
      vars:
        w_cfg_net_adapter_two_adapters: true
        w_cfg_net_adapter_adapter: "{{ plbr_nat_adapter }}"
        w_cfg_net_adapter_action: "disable"
    - name: Base setup
      ansible.builtin.include_role:
        name: "windows_cfg_base"
      when: ansible_hostname != plbr_hostname
    - name: Keyboard setup
      ansible.builtin.include_role:
        name: "windows_cfg_keyboard"
      when: ansible_hostname != plbr_hostname and plbr_is_server_os
    - name: Update Windows
      ansible.builtin.include_role:
        name: "windows_cfg_updates"
      when: ansible_hostname != plbr_hostname and plbr_update_initial
    - name: Update planning setup
      ansible.builtin.include_role:
        name: "windows_cfg_update_planning"
      when: ansible_hostname != plbr_hostname and plbr_update_continuous
    - name: Prevent update
      ansible.builtin.include_role:
        name: "windows_cfg_updates_stop"
      when: ansible_hostname != plbr_hostname and not plbr_update_continuous
    - name: Admin password setup
      ansible.builtin.include_role:
        name: "windows_cfg_admin_password"
      when: ansible_hostname != plbr_hostname
    - name: Hostname setup
      ansible.builtin.include_role:
        name: "windows_cfg_hostname"
      when: ansible_hostname != plbr_hostname
    - name: Hostname setup
      ansible.builtin.include_role:
        name: "windows_cfg_hostname"
      when: ansible_hostname != plbr_hostname
    - name: Register ansible_hostname for cache
      ansible.builtin.set_fact:
        ansible_hostname: "{{ plbr_hostname }}"
        cacheable: true
      when: ansible_hostname != plbr_hostname
  vars:
    w_cfg_kbd_layout: "0000040C"
    w_cfg_base_winrm_allow_ip: "{{ []  + [plbr_ansible_controller_ip] }}"
    w_cfg_base_rdp_allow_ip: "{{ []  + [plbr_ansible_controller_ip] }}"
    w_cfg_base_any_allow_ip: "{{ []  + [plbr_ansible_controller_ip] }}"
    w_cfg_hostname_name: "{{ plbr_hostname }}"
    w_cfg_base_force_dns_server: "{{ plbr_force_dns_server }}"
    w_cfg_base_dns_server: "{{ plbr_dns_server }}"
    w_cfg_base_enable_http_proxy: "{{ plbr_enable_http_proxy }}"
    w_cfg_base_http_proxy: "{{ plbr_http_proxy }}"
    w_cfg_base_https_proxy: "{{ plbr_https_proxy }}"
    w_cfg_base_two_adapters: "{{ plbr_two_adapters }}"
    w_cfg_base_domain_adapter: "{{ plbr_domain_adapter }}"
    w_cfg_lap_password: "{{ plbr_local_admin_password }}"
