---
- name: ROOT DC AD BUILD
  hosts: dc
  max_fail_percentage: 0
  tags: 'build_domains_parents_domains'
  roles:
    - { role: 'windows_domain_domain_root', tags: 'dc_main_domains', when: "dc_level == 0"}
    - { role: 'windows_domain_default_site_rename', tags: 'dc_main_domains', when: "dc_level == 0"}

- name: CHILD DC AD BUILD
  hosts: dc
  gather_facts: false
  max_fail_percentage: 0
  tags: 'build_domains_child_domains'
  roles:
    - { role: 'windows_domain_domain_child', tags: 'child_domain', when: "dc_level == 1"}
    - { role: 'windows_domain_dns_conditional_forwarder', tags: 'dns_conditional_forwarder', when: "dc_level == 1" }
  vars:
    master_server: "{{ domain_parent_dc_ip }}"
    zone_name: "{{ domain_parent_domain_name }}"
    replication: "none"
    site_name: "{{ default_first_site_name }}"

- name: ROOT DC ADD DNS CONFIGURATION
  hosts: dc
  max_fail_percentage: 0
  roles:
    - { role: 'windows_domain_dns_parent_forward', tags: 'child_dns', when: "dc_level == 0 and child_domains is defined"}


- name: ROOT DC ADD SUBNETS
  hosts: dc
  max_fail_percentage: 0
  roles:
    - { role: 'windows_domain_replication_subnet',when: "dc_level == 0" }
  vars: 
    wdrs_subnets: "{{ subnets }}"
    wdrs_site_name: "{{ default_first_site_name }}"
