---
- name: TRUSTS CONFIGURATION PREPARE
  hosts: trust
  max_fail_percentage: 0
  roles:
    - { role: 'windows_settings_manage_net_adapter', tags: 'disable_nat_adapter'}
    # dc forward trusted zone
    - { role: 'windows_domain_dns_conditional_forwarder', tags: 'dns_conditional_forwarder' }
  vars:
    zone_name: "{{ domain_trust_remote_domain_name  }}"
    master_server: "{{ domain_trust_remote_dc_ip  }}"
    replication: "forest"
    adapter: pub_adapter
    adapter_action: "disable"

- name: TRUSTS CONFIGURATION
  hosts: trust
  max_fail_percentage: 0
  gather_facts: false
  serial: 1 # add one trust at a time to avoid issues
  roles:
    - { role: 'windows_domain_trusts_create', tags: 'trust' }


- name: TRUSTS CONFIGURATION END
  hosts: trust
  max_fail_percentage: 0
  gather_facts: false
  roles:
    - { role: 'windows_settings_manage_net_adapter', tags: 'disable_nat_adapter'}
    # add DNS conditional forwarder on all trust dc for each other subdomains
    - { role: 'windows_domain_dc_dns_conditional_forwarder', tags: 'dns_conditional_forwarder', when: transitive_trusts_domains is defined }
  vars:
    replication: "forest"
    forward_info: "{{ transitive_trusts_domains  }}"
    adapter: pub_adapter
    adapter_action: "disable"

- name: TRUSTS CONFIGURATION
  hosts: trust
  max_fail_percentage: 0
  roles:
    - { role: 'windows_domain_trusts_check', tags: 'trust' }
