---
- name: ADCS INSTALL
  hosts: adcs
  max_fail_percentage: 0
  roles:
    - { role: 'windows_domain_adcs_templates', tags: 'adcs_templates', when: cert_templates is defined and cert_templates|length > 0}
