---
- name: ROOT DC AD CONFIGURATION
  hosts: dc
  max_fail_percentage: 0
  tags: 'build_domains_parents_domains'
  roles:
    - { role: 'windows_domain_domain_root', tags: 'dc_main_domains', when: "dc_level == 0"}


- name: CHILD DC AD CONFIGURATION
  hosts: dc
  gather_facts: false
  max_fail_percentage: 0
  tags: 'build_domains_child_domains'
  roles:
    - { role: 'windows_domain_domain_child', tags: 'child_domain', when: "dc_level == 1"}
    # child forward parent zone
    - { role: 'windows_domain_dns_conditional_forwarder', tags: 'dns_conditional_forwarder', when: "dc_level == 1" }
  vars:
    master_server: "{{ domain_parent_dc_ip }}"
    zone_name: "{{ domain_parent_domain_name }}"
    replication: "none"

# parent add DNS value of child DC
- name: Parent DC ADD DNS configuration
  hosts: dc
  max_fail_percentage: 0
  roles:
    - { role: 'windows_domain_child_dns', tags: 'child_dns'}
