---
- name: TRUSTS CONFIGURATION PREPARE
  hosts: trust
  gather_facts: false
  max_fail_percentage: 0
  tasks:
    - name: Disable NAT adapter
      ansible.builtin.include_role:
        name: windows_cfg_manage_net_adapter
    - name: Add conditionnal forwarder
      ansible.builtin.include_role:
        name: windows_domain_dns_conditional_forwarder
  vars:
    wd_dns_forwarder_domain_password: "{{ plbr_domain_password }}"
    wd_dns_forwarder_domain_name: "{{ plbr_domain_name }}"
    wd_dns_forwarder_zone_name: "{{ plbr_domain_trust_remote_domain_name }}"
    wd_dns_forwarder_master_server: "{{ plbr_domain_trust_remote_dc_ip }}"
    wd_dns_forwarder_replication: "forest"
    w_cfg_net_adapter_two_adapters: "{{ plbr_two_adapters }}"
    w_cfg_net_adapter_adapter: "{{ plbr_pub_adapter }}"
    w_cfg_net_adapter_action: "disable"

- name: TRUSTS CONFIGURATION
  hosts: trust
  max_fail_percentage: 0
  gather_facts: false
  serial: 1 # add one trust at a time to avoid issues
  tasks:
    - name: Build trust
      ansible.builtin.include_role:
        name: windows_domain_build_trust
  vars:
    wd_build_trust_remote_domain_name: "{{ plbr_domain_trust_remote_domain_name }}"
    wd_build_trust_remote_domain_password: "{{ plbr_domain_trust_remote_domain_password }}"
    wd_build_trust_domain_name: "{{ plbr_domain_name }}"
    wd_build_trust_domain_password: "{{ plbr_domain_password }}"


- name: TRUSTS CONFIGURATION END
  hosts: trust
  max_fail_percentage: 0
  gather_facts: false
  tasks:
    - name: Enable NAT adapter
      ansible.builtin.include_role:
        name: windows_cfg_manage_net_adapter
    - name: Add conditionnal forwarder to children
      ansible.builtin.include_role:
        name: windows_domain_dc_dns_conditional_forwarder
      when: plbr_domain_trust_transitive_domains is defined

  vars:
    w_cfg_net_adapter_two_adapters: "{{ plbr_two_adapters }}"
    w_cfg_net_adapter_adapter: "{{ plbr_pub_adapter }}"
    w_cfg_net_adapter_action: "enable"
    wd_dns_dc_forwarder_replication: "forest"
    wd_dns_dc_forwarder_forward_info: "{{ plbr_domain_trust_transitive_domains  }}"


- name: TRUSTS DEBUG
  hosts: trust
  max_fail_percentage: 0
  gather_facts: false
  tasks:
    - name: Debug trusts
      ansible.builtin.include_role:
        name: windows_domain_check_trust
  vars:
    wd_check_trust_domain_name: "{{ plbr_domain_name }}"
    wd_check_trust_domain_password: "{{ plbr_domain_password }}"
