---
- name: DCS AD DATA password policy
  hosts: dc
  max_fail_percentage: 0
  roles:
    - { role: 'windows_domain_password_policy', tags: 'policy'}
  vars:
    policy: "{{ password_policy.default }}"

- name: DCS AD DATA Create objects
  hosts: dc
  max_fail_percentage: 0
  roles:
    - { role: 'windows_domain_data_group', tags: 'ad_domain_data'}
    - { role: 'windows_domain_data_user', tags: 'ad_domain_data'}
    - { role: 'windows_domain_data_computer', tags: 'ad_domain_data'}
    - { role: 'windows_domain_gmsa_ad', tags: 'ad_domain_data'}
  vars:
    ad_groups: "{{ domain_groups }}"
    ad_users: "{{ domain_users }}"
    ad_computers: "{{ domain_computers }}"
    ad_gmsas: "{{ domain_gmsa }}"
    domain_data_action: "create"

- name: DCS AD DATA Add group members
  hosts: dc
  max_fail_percentage: 0
  roles:
    - { role: 'windows_domain_data_group', tags: 'ad_domain_data'}
  vars:
    ad_groups: "{{ domain_groups }}"
    domain_data_action: "add_members"

- name: DCS AD DATA Add group members (builtin groups)
  hosts: dc
  max_fail_percentage: 0
  roles:
    - { role: 'windows_domain_data_group', tags: 'ad_domain_data'}
  vars:
    ad_groups: "{{ domain_builtin_groups }}"
    domain_data_action: "add_members"

- name: DCS AD DATA Add delegates on objects
  hosts: dc
  max_fail_percentage: 0
  roles:
    - { role: 'windows_domain_gmsa_ad', tags: 'ad_domain_data'}
    - { role: 'windows_domain_data_user', tags: 'ad_domain_data'}
    - { role: 'windows_domain_data_computer', tags: 'ad_domain_data'}
  vars:
    ad_users: "{{ domain_service_accounts }}"
    ad_computers: "{{ domain_computers }}"
    ad_gmsas: "{{ domain_gmsa }}"
    domain_data_action: "add_delegates"

- name: DCS AD DATA Add kerberos delegations on service accounts
  hosts: dc
  max_fail_percentage: 0
  roles:
    - { role: 'windows_domain_kerberos_delegation', tags: 'ad_domain_data'}
  vars:
    objects: "{{ domain_service_accounts }}"

- name: DCS AD DATA Add kerberos delegations on gmsa accounts
  hosts: dc
  max_fail_percentage: 0
  roles:
    - { role: 'windows_domain_kerberos_delegation', tags: 'ad_domain_data'}
  vars:
    objects: "{{ domain_gmsa }}"

- name: DCS AD DATA Add kerberos delegations on computer accounts
  hosts: dc
  max_fail_percentage: 0
  roles:
    - { role: 'windows_domain_kerberos_delegation', tags: 'ad_domain_data'}
  vars:
    objects: "{{ domain_computers }}"

- name: DCS AD DATA Set UAC on gmsa accounts
  hosts: dc
  max_fail_percentage: 0
  roles:
    - { role: 'windows_domain_ad_account_control', tags: 'ad_domain_data'}
  vars:
    objects: "{{ domain_gmsa }}"

- name: DCS AD DATA Set UAC on user accounts
  hosts: dc
  max_fail_percentage: 0
  roles:
    - { role: 'windows_domain_ad_account_control', tags: 'ad_domain_data'}
  vars:
    objects: "{{ domain_users }}"

- name: DCS AD DATA Set UAC on computer accounts
  hosts: dc
  max_fail_percentage: 0
  roles:
    - { role: 'windows_domain_ad_account_control', tags: 'ad_domain_data'}
  vars:
    objects: "{{ domain_computers }}"

- name: "DCS AD DATA GPOs Management"
  hosts: dc
  max_fail_percentage: 0
  tasks:
    - name: Install GPO
      ansible.builtin.include_role:
        name: "windows_domain_gpo"
      vars:
        windows_domain_gpo_ous: "{{ g.value.gpo_ous }}"
        windows_domain_gpo_name: "{{ g.key }}"
        windows_domain_gpo_desc: "{{ g.value.gpo_desc }}"
        windows_domain_gpo_registry: "{{ g.value.gpo_registry }}"
        windows_domain_gpo_domain: "{{ g.value.gpo_domain }}"
        windows_domain_gpo_domain_enforced: "{{ g.value.gpo_domain_enforced }}"
        windows_domain_gpo_domain_enabled: "{{ g.value.gpo_domain_enabled }}"
        windows_domain_gpo_domain_state: "{{ g.value.gpo_domain_state }}"
      loop: "{{ gpo | dict2items }}"
      loop_control:
        loop_var: g
