---
- name: ORGANIZATIONAL UNITES CONFIGURATION
  hosts: dc
  max_fail_percentage: 0
  tags: 'domain_cfg_ou'
  tasks:
    - name: Base setup
      ansible.builtin.include_role:
        name: "windows_domain_cfg_ou"
  vars:
    wd_cfg_ou_ous: "{{ plbr_domain_ous }}"
    wd_cfg_ou_domain_name: "{{ plbr_domain_name }}"
    wd_cfg_ou_domain_password: "{{ plbr_domain_password }}"
