---
- name: ENSURE DOMAINS ARE REACHABLE
  hosts: firewalls
  become: true
  max_fail_percentage: 0
  become_user: root
  tasks:
    - name: Add routes to domains
      ansible.builtin.include_tasks: tasks/ensure-reachable.yml
      vars:
        info: "{{ hostvars[inventory_hostname].ansible_facts }}"
        interface: "{{ item }}"
        via: "{{ ansible_host }}"
      with_items: "{{ domains_interfaces }}"
