---
- name: ENSURE DOMAIN MEMBER DNS IS SETUP
  hosts: domain_server, domain_workstation
  max_fail_percentage: 0
  gather_facts: false
  roles:
    - { role: 'windows_domain_member_dns', tags: 'gmsa'}
  vars:
    wd_mbr_dns_domain_adapter: "{{ plbr_domain_adapter }}"
    wd_mbr_dns_two_adapters: "{{ plbr_two_adapters }}"
    wd_mbr_dns_domain_dc_ip: "{{ plbr_domain_dc_ip }}"

- name: INSTALL GMSA ON DOMAIN MEMBERS
  hosts: domain_server, domain_workstation
  max_fail_percentage: 0
  gather_facts: false
  roles:
    - { role: 'windows_domain_gmsa_install', tags: 'gmsa'}
  vars:
    wd_gmsa_install_domain_name: "{{ plbr_domain_name }}"
    wd_gmsa_install_domain_password: "{{ plbr_domain_password }}"
    wd_gmsa_install_installed_gmsa: "{{ plbr_domain_installed_gmsa }}"

- name: CONFIGURE LAPS ON DOMAIN MEMBERS
  hosts: domain_server,  domain_workstation
  max_fail_percentage: 0
  gather_facts: false
  roles:
    - { role: 'windows_domain_laps_member', tags: 'laps-server', when: plbr_domain_laps_path  | length > 0 and plbr_use_laps == true }

- name: VERIFY AND SHOW LAPS PASSWORDS ON DOMAIN MEMBERS
  hosts: dc
  max_fail_percentage: 0
  gather_facts: false
  roles:
    - { role: 'windows_domain_laps_verify', tags: 'laps-verify', when: plbr_domain_laps_path  | length > 0}
  vars:
    wd_laps_verify_hosts_dict: "{{ hostvars}} "
