---


- name: "INSTALL MSSQL EXPRESS"
  hosts: mssql
  max_fail_percentage: 0
  gather_facts: false
  roles:
    - { role: 'windows_domain_mssql_build_mssql', tags: 'mssql'}
  vars:
    isgmsa: "{{ true if plbr_mssql_svcaccount_method == 'gmsa' else false }}"
    sql_instance_name: "{{ plbr_mssql_instance_name }}"
    sql_version: "{{ plbr_mssql_version }}"
    sql_svc_account: "{{ plbr_sql_svcaccount_name }}"
    config_sql_svc_account: "{{ plbr_config_sql_svcaccount }}"
    sql_svc_password: "{{ plbr_sql_svcaccount_password }}"
    sql_admin: "{{ plbr_sql_svcaccount_name }}"
    sa_password: "{{ plbr_mssql_sa_password }}"
    domain_name: "{{ plbr_domain_name }}"
    domain_password: "{{ plbr_domain_password }}"
    mssql_svcaccount_method: "{{ plbr_mssql_svcaccount_method }}"

- name: "INSTALL MSSQL  SERVER REPORTING"
  hosts: mssql_reporting
  max_fail_percentage: 0
  gather_facts: false
  roles:
    - { role: 'windows_domain_mssql_build_reporting', tags: 'mssql_reporting'}
  vars:
    wd_mssql_build_reporting_domain_name: "{{ plbr_domain_name }}"
    wd_mssql_build_reporting_domain_password: "{{ plbr_domain_password }}"


- name: "INSTALL SQL SERVER MANAGEMENT STUDIO"
  hosts: mssql_ssms
  gather_facts: false
  roles:
    - { role: 'windows_domain_mssql_build_ssms', tags: 'mssql_ssms'}
