---
# Load datas
- name: "INSTALL MSSQL EXPRESS"
  hosts: mssql
  max_fail_percentage: 0
  tasks:
    - name: set service account login password
      ansible.builtin.set_fact:
        sql_svcaccount_name: "{{mssql_svcaccount_local | default('')}}"
        sql_svcaccount_password: ""

    - name: set service account login as domain service
      ansible.builtin.set_fact:
        sql_svcaccount_name: "{{domain_name}}\\{{mssql_svcaccount_key}}"
      when: mssql_svcaccount_method == 'domain'

    - name: set service account login as gmsa
      ansible.builtin.set_fact:
        sql_svcaccount_name: "{{domain_name}}\\{{mssql_svcaccount_key}}$"
      when: mssql_svcaccount_method == 'gmsa'

    - name: set service account password for domain service
      ansible.builtin.set_fact:
        sql_svcaccount_password: "{{hostvars[domain_dc_ansible_inventory_key].domain_users[mssql_svcaccount_key].password}}"
      when: mssql_svcaccount_method == 'domain'

#    - name: print some vars
#      debug:
#        msg: 
#          - "SQLSVCACCOUNT: {{sql_svcaccount_name}}"
#          - "SQLSVCPASSWORD: {{sql_svcaccount_password}}"
#          - "sql_sysadmins: {{mssql_sysadmins | default([]) }}"
#          - "executeaslogin: {{mssql_executeaslogin  | default({}) }}"
#          - "executeasuser:  {{mssql_executeasuser | default({}) }}"
#          - "sa_password: {{mssql_sa_password}}"
#          - "linked_servers: {{mssql_linked_servers | default({}) }}"

- name: "INSTALL MSSQL EXPRESS"
  hosts: mssql
  max_fail_percentage: 0
  roles:
    - { role: 'windows_domain/mssql/mssql', tags: 'mssql'}
    - { role: 'windows_domain/mssql/mssql_link', tags: 'mssql, mssql_link'}
  vars:
    ISGMSA: "{{true if mssql_svcaccount_method == 'gmsa' else false}}" 
    sql_instance_name: "{{mssql_instance_name}}"
    SQLSVCACCOUNT: "{{sql_svcaccount_name}}"
    SQLSVCPASSWORD: "{{sql_svcaccount_password}}"
    SQLYSADMIN: "{{sql_svcaccount_name}}"
    sql_sysadmins: "{{mssql_sysadmins | default([]) }}"
    executeaslogin: "{{mssql_executeaslogin  | default({}) }}"
    executeasuser:  "{{mssql_executeasuser | default({}) }}"
    sa_password: "{{mssql_sa_password}}"
    linked_servers: "{{mssql_linked_servers | default({}) }}"

- name: "INSTALL SQL SERVER MANAGEMENT STUDIO"
  hosts: mssql_ssms
  roles:
    - { role: 'windows_domain/mssql/mssql_ssms', tags: 'mssql_ssms'}
