
- name: GET BACK TLS SERVER TEMPLATE OID
  hosts: adcs
  max_fail_percentage: 0
  gather_facts: false
  tasks:
    - name: Block
      when: plbr_tls_server_certificate_template_name is defined and plbr_tls_server_certificate_template_name != ""
      block:
        - name: Get TSL Server Template OID
          ansible.windows.win_powershell:
            script: |
              [CmdletBinding()]
              param (
                  [String]
                  $TemplateName
              )
              $Ansible.Failed = $false
              $Ansible.Changed = $false

              $template = Get-CATemplate | where {$_.name -match $TemplateName}
              $Ansible.Result = $template.OID
            parameters:
              TemplateName: "{{ plbr_tls_server_certificate_template_name }}"
          register: template_oid_result

        - name: Register plbr_tls_server_certificate_template_oid
          ansible.builtin.set_fact:
            plbr_tls_server_certificate_template_oid: "{{ template_oid_result.result }}"
            cacheable: true



- name: NPS Setup
  hosts: nps
  tags: nps_build
  max_fail_percentage: 0
  gather_facts: false
  tasks:
    - name: Register plbr_adcs_server_key
      ansible.builtin.set_fact:
        plbr_tls_server_certificate_template_oid: "{{ hostvars[plbr_adcs_server_key].plbr_tls_server_certificate_template_oid }}"
        cacheable: true
    - name: Install NPS Role
      ansible.builtin.include_role:
        name: "windows_domain_nps_build_nps"
#    - name: Install NPS Role
#      ansible.builtin.include_role:
#        name: "windows_domain_nps_cfg_nas"
    - name: Configure NPS
      ansible.builtin.include_role:
        name: "windows_domain_nps_cfg_load"
  vars:
    nps_domain_name: "{{ plbr_domain_name }}"
    nps_domain_password: "{{ plbr_domain_password }}"
    nps_config_replace: "{{ nps_group_sid_replace }}"
    nps_certificate_template_oid: "{{ plbr_tls_server_certificate_template_oid }}"
