---
- name: "INSTALL USER DATA ON MEMBERS"
  hosts: domain_server, domain_workstation
  tasks:
    - name: Install softwares
      ansible.builtin.include_role:
        name: "windows_domain_install_softwares"
      when: softwares | default([]) | length > 0

    - name: Clone repos
      ansible.builtin.include_role:
        name: "windows_domain_clone_repos"
      vars:
        windows_domain_clone_repos_repositories: "{{ u.value }}"
        windows_domain_clone_repos_user: "{{ u.key }}"
        windows_domain_clone_repos_net_bios: "{{ domain_netbios_name }}"
        windows_domain_clone_repos_password: "{{ hostvars[domain_dc_ansible_inventory_key].domain_users_regular[u.key].password }}"
      loop: "{{ user_repos | dict2items }}"
      when: user_repos is defined
      loop_control:
        loop_var: u

    - name: Donwload files
      ansible.builtin.include_role:
        name: "windows_domain_download_files"
      loop: "{{ user_downloads | dict2items }}"
      loop_control:
        loop_var: u
      when: user_downloads is defined
      vars:
        windows_domain_download_files_downloads: "{{ u.value }}"
        windows_domain_download_files_user: "{{ u.key }}"
        windows_domain_download_files_net_bios: "{{ domain_netbios_name }}"
        windows_domain_download_files_password: "{{ hostvars[domain_dc_ansible_inventory_key].domain_users_regular[u.key].password }}"
