---
- name: JOIN SERVERS TO DOMAIN
  hosts: domain_server
  max_fail_percentage: 0
  gather_facts: false
  tags: 'domain_join_server'
  tasks:
    - name: Join servers
      ansible.builtin.include_role:
        name: windows_domain_join_server
      when: not ansible_windows_domain_member

    - name: Install features
      ansible.builtin.include_role:
        name: windows_domain_member_features
      when: not ansible_windows_domain_member

    - name: Register ansible_windows_domain_member for cache
      ansible.builtin.set_fact:
        ansible_windows_domain_member: true
        cacheable: true
      when: not ansible_windows_domain_member
  vars:
    wd_join_srv_domain_adapter: "{{ plbr_domain_adapter }}"
    wd_join_srv_two_adapters: "{{ plbr_two_adapters }}"
    wd_join_srv_domain_dc_ip: "{{ plbr_domain_dc_ip }}"
    wd_join_srv_domain_name: "{{ plbr_domain_name }}"
    wd_join_srv_hostname: "{{ plbr_hostname }}"
    wd_join_srv_domain_password: "{{ plbr_domain_password }}"
    wd_join_srv_path: "{{ plbr_domain_path }}"
    wd_mbr_features_features: "{{ plbr_extra_features }}"

- name: JOIN WORKSTATIONS TO DOMAIN
  hosts: domain_workstation
  max_fail_percentage: 0
  gather_facts: false
  tags: 'domain_join_workstation'
  tasks:
    - name: Join servers
      ansible.builtin.include_role:
        name: windows_domain_join_workstation
      when: not ansible_windows_domain_member

    - name: Install capabilities
      ansible.builtin.include_role:
        name: windows_domain_member_capabilities
      when: not ansible_windows_domain_member

    - name: Register ansible_windows_domain_member for cache
      ansible.builtin.set_fact:
        ansible_windows_domain_member: true
        cacheable: true
      when: not ansible_windows_domain_member
  vars:
    wd_join_wks_domain_adapter: "{{ plbr_domain_adapter }}"
    wd_join_wks_two_adapters: "{{ plbr_two_adapters }}"
    wd_join_wks_domain_dc_ip: "{{ plbr_domain_dc_ip }}"
    wd_join_wks_domain_name: "{{ plbr_domain_name }}"
    wd_join_wks_hostname: "{{ plbr_hostname }}"
    wd_join_wks_domain_password: "{{ plbr_domain_password }}"
    wd_join_wks_path: "{{ plbr_domain_path }}"
    wd_mbr_capab_capabilities: "{{ plbr_extra_capabilities }}"
