---
- name: "SCCM"
  hosts: dc
  tasks:
    - include_role:
        name: "windows_domain/dhcp"
      vars:
        dns_ip: "{{ansible_host}}"
        ip_root: "{{'.'.join(dns_ip.split('.')[:3])}}"
        ip_from: "{{ip_root}}.{{dhcp[0]}}"
        ip_to: "{{ip_root}}.{{dhcp[1]}}"
        ip_mask: "{{dhcp[2]}}"
        lease_duration: "{{dhcp[3]}}"
        dc_fqdn: "{{domain_dc_name}}"
      when: dhcp is defined
    - include_role:
        name: "windows_domain/sccm/install_extend_adschema"
      when: sccm_server | length > 0

- name: "INSTALL SCCM"
  hosts: sccm
  max_fail_percentage: 0
  roles:
    - { role: 'windows_domain/sccm/install_iis', tags: 'sccm_iis'}
    - { role: 'windows_domain/sccm/install_adk', tags: 'sccm_adk'}
    - { role: 'windows_domain/sccm/install_wsus', tags: 'sccm_wsus'}
    - { role: 'windows_domain/sccm/install_mecm', tags: 'sccm_mecm'}