- name: "Exchange Setup"
  hosts: dc
  tags: xchg_prerequisites
  max_fail_percentage: 0
  tasks:
    - name: Active Directory Prerequisits
      ansible.builtin.include_role:
        name: "windows_domain_exchange_extend_schema"
      vars:
        wd_xchg_es_corp_name: "{{ exchange_corp_name }}"
        wd_xchg_es_multi_domain_forest: "{{ multi_domain_forest }}"
      when: exchange_corp_name is defined


- name: "Exchange Setup"
  hosts: exchange
  tags: xchg_build
  max_fail_percentage: 0
  tasks:
    - name: Install Exchange Mailbox role
      ansible.builtin.include_role:
        name: "windows_domain_exchange_install_mailbox"
      vars:
        wd_xchg_im_corp_name: "{{ hostvars[domain_dc_ansible_inventory_key].exchange_corp_name }}"

- name: "Exchange Setup"
  hosts: exchange
  tags: xchg_config
  max_fail_percentage: 0
  tasks:
    - name: Configure Exchange
      ansible.builtin.include_role:
        name: "windows_domain_exchange_cfg"
      vars:
        wd_xchg_cfg_corp_name: "{{ hostvars[domain_dc_ansible_inventory_key].exchange_corp_name }}"
        wd_xchg_cfg_action: "{{ item }}"
      with_items:
        - dns
        - connector
        - mailbox
        - security
  