- name: Exchange Prerequisites
  hosts: dc
  tags: xchg_prerequisites
  max_fail_percentage: 0
  gather_facts: false
  tasks:
    - name: Active Directory Prerequisits
      ansible.builtin.include_role:
        name: "windows_domain_xchg_extend_schema"
      when: plbr_exchange_corp_name is defined


- name: Exchange Setup
  hosts: exchange
  tags: xchg_build
  max_fail_percentage: 0
  gather_facts: false
  tasks:
    - name: Install Exchange Mailbox role
      ansible.builtin.include_role:
        name: "windows_domain_xchg_install_mailbox"

- name: Exchange Config
  hosts: exchange
  tags: xchg_config
  gather_facts: false
  max_fail_percentage: 0
  tasks:
    - name: Configure Exchange
      ansible.builtin.include_role:
        name: "windows_domain_xchg_cfg"
      vars:
        windows_domain_xchg_cfg_action: "{{ item }}"
      with_items:
        - dns
        - connector
        - mailbox
        - security
