---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../ad/{{domain_name}}/data/"
  tags: 'data'

- name: "Disable vagrant"
  hosts: domain
  roles:
    - { role: 'disable_vagrant', tags: 'disable_vagrant', status: true}