
local_users: {
    "arose" : {
        "password"        : "z77w_TeCUCD_wLrD", 
        "groups"          : ["Remote Management Users", "Administrators"]
        },
    "LA_jubeaz" : {
        "password"        : "Jubeaz12345+-", 
        "groups"          : ["Administrators"]
        }
}


local_groups: {
    "Administrators" : [".\\arose"],
    "Remote Management Users": ["weyland.local\\arose"],
    "Remote Desktop Users" : [],
}



scripts : ["sidhistory.ps1"]
vulns: ["disable_firewall"]