
#domain_password : "Jubeaz12345+-"
domain_netbios_name: "RESEARCH"
domain_name: "research.haas.local"


trust_domain_dc_ansible_inventory_key : "" # ansible inventory name
parent_domain_dc_ansible_inventory_key: "dc_haas" # ansible inventory name


