local_groups: {
    "Administrators" : ["haas.local\\L_LOCAL_ADMINS"]
#    "Remote Desktop Users" : [],
#    "Remote Management Users": []
}


local_users: {
    "LA_jubeaz" : {
        "password"        : "jubeaz", 
        "groups"          : ["Administrators"]
        }
}

# Get-WindowsCapability -Name RSAT* -Online | Select-Object -Property DisplayName, State
extra_features: [
    "Rsat.CertificateServices.Tools~~~~0.0.1.0",
    "Rsat.ActiveDirectory.DS-LDS.Tools~~~~0.0.1.0",
    "Rsat.Dns.Tools~~~~0.0.1.0",
    "Rsat.FileServices.Tools~~~~0.0.1.0",
    "Rsat.GroupPolicy.Management.Tools~~~~0.0.1.0",
    "Rsat.RemoteAccess.Management.Tools~~~~0.0.1.0",
    "Rsat.RemoteDesktop.Services.Tools~~~~0.0.1.0",
    "Rsat.ServerManager.Tools~~~~0.0.1.0",
    "Rsat.DHCP.Tools~~~~0.0.1.0"
]



#features: ["NET-Framework-Core"]
softwares: [  "git", "visualstudio2022community", "notepadplusplus", "python"]

user_repos: {
    jubeaz: [
        ["Mimikatz", "https://github.com/gentilkiwi/mimikatz.git"],
        ["Rubeus", "https://github.com/GhostPack/Rubeus"]
    ]
}
user_downloads: {
    jubeaz: [
        ["GRMWDK_EN_7600_1.ISO", "https://download.microsoft.com/download/4/A/2/4A25C7D5-EFBE-4182-B6A9-AE6850409A78/GRMWDK_EN_7600_1.ISO"]
    ]
}


