#plbr_mssql_instance_name: "{{hostname}}"
plbr_mssql_sa_password: "rWCUe2D3sMJtYHwd8V_FnB"
plbr_mssql_svcaccount_method: 'local' # domain, gmsa, local
plbr_mssql_svcaccount_local: NetworkService #  "NetworkService, System, LocalService"'
# NT AUTHORITY\NetworkService
#plbr_mssql_svcaccount_method: 'domain' # domain, gmsa, local
#plbr_mssql_svcaccount_key: "eli" # default : 'NT AUTHORITY\\NETWORK SERVICE'


#plbr_mssql_sysadmins: ["WEYLAND\\acorrea", "WEYLAND\\wubeaz"]
plbr_mssql_sysadmins: ["WEYLAND\\G_SYSADMIN_ARCHER"]
plbr_mssql_domain_accounts: ["WEYLAND\\G_SQL_ACCOUNTS_ARCHER"]

plbr_mssql_local_accounts: {
    "link_account": "xTmjUz7k8DJg2_HYq6Ph3V"
}

plbr_mssql_executeaslogin: {
#  "WEYLAND\\anson" :  "WEYLAND\\acorrea"
}
plbr_mssql_executeasuser: {
#  "master_dbo": {
#    "user": "WEYLAND\\acorrea",
#    "db"  : "master",
#    "impersonate" : "dbo"
#    },
#  "dbms_dbo": {
#    "user": "WEYLAND\\acorrea",
#    "db"  : "msdb",
#    "impersonate" : "dbo"
#    }
  }
plbr_mssql_linked_servers: {
#  "fenris" : {
#    "data_src": "bran.haas.local",
#    "users_mapping": [
#      {"local_login": "WEYLAND\\acorrea","remote_login": "sa", "remote_password": "ftrum_Ya5d7DCQQN"}
#      ]
#  }
  "fenris" : {
    "data_src": "eli.haas.local",
    "users_mapping": [
      {"local_login": "sa","remote_login": "link_account", "remote_password": "nQAhqFRaBJ9XxgC6WYT_tM"}
      ]
  }
}
