#mssql_instance_name: "{{hostname}}"
mssql_sa_password: "rWCUe2D3sMJtYHwd8V_FnB"
mssql_svcaccount_method: 'local' # domain, gmsa, local
mssql_svcaccount_local: NetworkService #  "NetworkService, System, LocalService"'
# NT AUTHORITY\NetworkService
#mssql_svcaccount_method: 'domain' # domain, gmsa, local
#mssql_svcaccount_key: "eli" # default : 'NT AUTHORITY\\NETWORK SERVICE'


#mssql_sysadmins: ["WEYLAND\\acorrea", "WEYLAND\\wubeaz"]
mssql_sysadmins: ["WEYLAND\\wubeaz"]

mssql_domain_accounts: ["WEYLAND\\wubeaz"]

mssql_local_accounts: {
    "link_account": "xTmjUz7k8DJg2_HYq6Ph3V"
}

mssql_executeaslogin: {
#  "WEYLAND\\anson" :  "WEYLAND\\acorrea"
}
mssql_executeasuser: {
#  "master_dbo": {
#    "user": "WEYLAND\\acorrea",
#    "db"  : "master",
#    "impersonate" : "dbo"
#    },
#  "dbms_dbo": {
#    "user": "WEYLAND\\acorrea",
#    "db"  : "msdb",
#    "impersonate" : "dbo"
#    }
  }
mssql_linked_servers: {
#  "fenris" : {
#    "data_src": "bran.haas.local",
#    "users_mapping": [
#      {"local_login": "WEYLAND\\acorrea","remote_login": "sa", "remote_password": "ftrum_Ya5d7DCQQN"}
#      ]
#  }
  "fenris" : {
    "data_src": "bran.haas.local",
    "users_mapping": [
      {"local_login": "sa","remote_login": "link_account", "remote_password": "nQAhqFRaBJ9XxgC6WYT_tM"}
      ]
  }
}
