#hostname: "wld01"
plbr_is_window_core: false

plbr_force_dns_server: yes
plbr_dns_server: 8.8.8.8

# proxy settings (the lab need internet for some install, if you are behind a proxy you should set the proxy here)
plbr_enable_http_proxy: no
plbr_http_proxy: http://x.x.x.x:xxxx
plbr_https_proxy: http://x.x.x.x:xxxx


plbr_two_adapters: "{{ true if public_ip is defined else false}}"
plbr_nat_adapter: Ethernet
plbr_domain_adapter: Ethernet 2
plbr_pub_adapter: Ethernet 3
