update_initial: true
update_continuous: false

enable_webdav: false

# 0: UAC won't prompt (like disabled)                                                                                                                                                                  │
# 1: ask for username and password to execute the binary with high rights (on Secure Desktop)                                                                                                          │
# 2: Always notify me ask for confirmation to the administrator when he tries to execute something with high privileges (on Secure Desktop)                                                            │
# 3: like 1 but not necessary on Secure Desktop                                                                                                                                                        │
# 4: like 2 but not necessary on Secure Desktop                                                                                                                                                        │
# 5: ask the administrator to confirm to run non Windows binaries with high privileges     
#uac_status_level: 5
enable_run_as_ppl: false
#windows_defender: true
windows_defender: false

connection_profiles: {
#  #"domain":  {"interface": "{{domain_adapter}}", "NetworkCategory": "Public", "IPv4Connectivity": "", "IPv6Connectivity": ""}
#  "public":  {"interface": "{{pub_adapter}}",     "NetworkCategory": "Public", "IPv4Connectivity": "LocalNetwork", "IPv6Connectivity": "Disconnected"}
}

firewall_profiles: {
  "Domain": {"enabled": "True", "inbound": "allow", "outbound": "allow"},
  "Public": {"enabled": "True", "inbound": "allow", "outbound": "allow"},
  "Private": {"enabled": "True", "inbound": "allow", "outbound": "allow"},
# enabled: True, False, NotConfigured
# inbound: Block, Allow, NotConfigured
# outbound: Block, Allow, NotConfigured
# key: ["Domain", "Private", "Public"], 
}

HardeningKitty: {
#  "Name": {
#    FileFindingList: "https://github.com/scipag/HardeningKitty/raw/refs/heads/master/lists/finding_list_cis_microsoft_windows_server_2022_22h2_3.0.0_machine.csv",
#    FileCriteria: "cis_microsoft_windows_server_2022_22h2_3.0.0_machine",
#    Filter: '$_.DC -eq "Y" -and $_.DEFAULT -eq "APPLY"',
#    FileOut: "findings_DC",
#  },
}

firewall_rules: {
#   "FTP_IN_1": {
#      "name": "FTP In",
#      "enabled": true, 
#      "action": "allow", 
#      "profiles": ["Domain"], 
#      "direction": "inbound", # inbound, outbound
#      "localip": ["any"], 
#      "localport": [21],  
#      "protocol": "tcp", # any or value
#      "remoteip": ["any"],  
#      "remoteport": ["any"] 
#      #"group": "ansible" # default ansible
#    },
#   "mssql_default_instance": {
#      "name": "SQLServer default instance",
#      "enabled": true, 
#      "action": "allow", 
#      "profiles": ["Domain"], 
#      "direction": "inbound", # inbound, outbound
#      "localip": ["any"], 
#      "localport": [1433],  
#      "protocol": "tcp", # any or value
#      "remoteip": ["172.16.0.10", "172.16.0.20"],  
#      "remoteport": ["any"] 
#      #"group": "ansible" # default ansible
#    },
#   "mssql_browser_service": {
#      "name": "SQLServer browser service",
#      "enabled": true, 
#      "action": "allow", 
#      "profiles": ["Domain"], 
#      "direction": "inbound", # inbound, outbound
#      "localip": ["any"], 
#      "localport": [1433],  
#      "protocol": "udp", # any or value
#      "remoteip": ["172.16.0.10", "172.16.0.20"],  
#      "remoteport": ["any"] 
#      #"group": "ansible" # default ansible
#    }
}

