---
ansible_user: vagrant
ansible_password: vagrant
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
ansible_winrm_operation_timeout_sec: 400
ansible_winrm_read_timeout_sec: 500
#ansible_winrm_transport: CredSSP
ansible_port:  5986

nat_adapter: Ethernet
domain_adapter: Ethernet 2
pub_adapter: Ethernet 3