
#-supports_check_mode $true

# "_ansible_check_mode" -type "bool" -default $false
# "_ansible_diff" -type "bool" -default $false
# "gpo" -type "str" -failifempty $true
# "name" -type "str" -failifempty $true
# "path" -type "str" -failifempty $true
# "state" -type "str" -default "present" -validateset "absent", "disabled", "present"
# "type" -type "str" -default "string" -ValidateSet "string", "expandstring", "binary", "dword", "multistring", "qword"
# "value"

# https://admx.help/?Category=security-compliance-toolkit

plbr_gpo_local: {
}


plbr_gpo:  "{{ gpo_global | combine(gpo_local) }}"