domain_real_computers: {
    "eli": {
        "name":             "eli",
        "dns_hostname":     "eli.haas.local",
        "description":      "mssql",
        "path":             "OU=Servers,OU=IT,OU=HQ,DC=haas,DC=local",            
        "delegates"       : [], # RBCD / must be DN msDS-AllowedToActOnBehalfOfOtherIdentity
        "delegation_type" : false, # "KCD", "KUD", false
        "constrained"     : [], # KCD / SPN list / msDS-AllowedToDelegateTo
        "proto_transition": false,  # KCD default false
        "sensitive"       : false
    },
    "bran": {
        "name":             "bran",
        "dns_hostname":     "bran.haas.local",
        "description":      "mecm iis wsus",
        "path":             "OU=Servers,OU=IT,OU=HQ,DC=haas,DC=local",            
        "delegates"       : [], # RBCD / must be DN msDS-AllowedToActOnBehalfOfOtherIdentity
        "delegation_type" : false, # "KCD", "KUD", false
        "constrained"     : [], # KCD / SPN list / msDS-AllowedToDelegateTo
        "proto_transition": false,  # KCD default false
        "sensitive"       : false
    },
}

domain_fake_computers: {
    "jaguarundi" : {
        "name":             "jaguarundi",
        "dns_hostname":     "jaguarundi.haas.local",
        "description":      "mssql",
        "path":             "OU=Servers,OU=IT,OU=HQ,DC=haas,DC=local",            
        "spns":             ["MSSQLSvc/Jaguarundi.haas.local:1433","MSSQLSvc/Jaguarundi.haas.local"],            
        "delegates"       : [], # RBCD / must be DN msDS-AllowedToActOnBehalfOfOtherIdentity
        "delegation_type" : false, # "KCD", "KUD", false
        "constrained"     : [], # KCD / SPN list / msDS-AllowedToDelegateTo
        "proto_transition": false,  # KCD default false
        "sensitive"       : false,
        "ADAC": {
            "AllowReversiblePasswordEncryption": true,
            "CannotChangePassword":              true,
            "PasswordNeverExpires":              true,
            "PasswordNotRequired":               true,
            "AccountNotDelegated":               true,
            "DoesNotRequirePreAuth":             true
        }  
    },
#    "ws01" : {
#        "name":             "ws01",
#        "dns_hostname":     "ws01.haas.local",
#        "path":             "OU=Workstations,OU=IT,OU=HQ,DC=haas,DC=local",
#        "spns":             ["cifs/ws01.haas.local"],                
#        "delegates"       : [], # RBCD / must be DN msDS-AllowedToActOnBehalfOfOtherIdentity
#        "delegation_type" : false, # "KCD", "KUD", false
#        "constrained"     : [], # KCD / SPN list / msDS-AllowedToDelegateTo
#        "proto_transition": false,  # KCD default false
#        "sensitive"       : false
#    },
#    "ws02" : {
#        "name":             "ws02",
#        "dns_hostname":     "ws02.haas.local",
#        "path":             "OU=Workstations,OU=IT,OU=HQ,DC=haas,DC=local",            
#        "spns":             ["cifs/ws02.haas.local"],                
#        "delegates"       : [], # RBCD / must be DN msDS-AllowedToActOnBehalfOfOtherIdentity
#        "delegation_type" : false, # "KCD", "KUD", false
#        "constrained"     : "KUD", # KCD / SPN list / msDS-AllowedToDelegateTo
#        "proto_transition": false,  # KCD default false
#        "sensitive"       : false
#    },
#    "ws03" : {
#        "name":             "ws03",
#        "dns_hostname":     "ws03.haas.local",
#        "path":             "OU=Workstations,OU=IT,OU=HQ,DC=haas,DC=local",            
#        "spns":             ["cifs/ws03.haas.local"],                
#        "delegates"       : [], # RBCD / must be DN msDS-AllowedToActOnBehalfOfOtherIdentity
#        "delegation_type" : "KCD", # "KCD", "KUD", false
#        "constrained"     : ["cifs/ws01", "cifs/ws01.haas.local"], # KCD / SPN list / msDS-AllowedToDelegateTo
#        "proto_transition": true,  # KCD default false
#        "sensitive"       : false
#    }
}
