domain_groups : {
    "G_LAPS_READER" : {
        "scope": "global", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=HQ,DC=haas,DC=local",
        "members" : [
        ]
    },
    "L_LAPS_READER" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=HQ,DC=haas,DC=local",
        "members" : [
        ]
    },
    "L_LOCAL_ADMINS" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "CN=Users,DC=haas,DC=local",
        "members" : [
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
    "L_LOCAL_ADMINS_ELI" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "CN=Users,DC=haas,DC=local",
        "members" : [
            "haas.local\\bran$"  # SCCM REQUIREMENTS ADIN OF MSSQL SERVER
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
    "G_CERT_MGR" : {
        "scope": "global", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=HQ,DC=haas,DC=local",
        "members" : [
        ]
    },
    "L_CERT_MGR" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=HQ,DC=haas,DC=local",
        "members" : [
            "G_CERT_MGR"
        ]
    },
    "L_LOCAL_ADMINS_BRAN" : {
        "scope": "domainlocal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "CN=Users,DC=haas,DC=local",
        "members" : [
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
    "G_SYSADMIN_ELI" : {
        "scope": "global", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "CN=Users,DC=haas,DC=local",
        "members" : [
            "HAAS\\jubeaz", 
            "HAAS\\administrator", 
            "HAAS\\drafter",
            "HAAS\\bran$"  # SCCM REQUIREMENTS ADIN OF MSSQL SERVER
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
    "G_SQL_ACCOUNTS_ELI" : {
        "scope": "global", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "CN=Users,DC=haas,DC=local",
        "members" : [
            "G_SYSADMIN_ELI"
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
    "G_SYSADMIN_FENRIS" : {
        "scope": "global", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "CN=Users,DC=haas,DC=local",
        "members" : [
            "HAAS\\jubeaz"
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
    "G_SQL_ACCOUNTS_FENRIS" : {
        "scope": "global", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "CN=Users,DC=haas,DC=local",
        "members" : [
            "HAAS\\G_SYSADMIN_FENRIS"
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
    "G_SCCM_ADMINS" : {
        "scope": "global", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=HQ,DC=haas,DC=local",
        "members" : [
            "HAAS\\hubeaz"
        ]
    },
    "U_SCCM_ADMINS" : {
        "scope": "universal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=HQ,DC=haas,DC=local",
        "members" : [
            "HAAS\\G_SCCM_ADMINS",
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": ["RESEARCH\\G_SCCM_ADMINS"]
    },
    "G_SCCM_MANAGED" : {
        "scope": "global", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=HQ,DC=haas,DC=local",
        "members" : [ 
            "bran$"
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
    "U_SCCM_MANAGED" : {
        "scope": "universal", # universal, global or domainlocal default domainlocal
        "managed_by" : "Domain Admins",
        "path" : "OU=Groups,OU=IT,OU=HQ,DC=haas,DC=local",
        "members" : [ 
            "HAAS\\G_SCCM_MANAGED",
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": ["RESEARCH\\G_SCCM_MANAGED"]
    },
}

#         "foreign_members": ["weyland.local\\G_LAPS_READER"]

domain_builtin_groups: {
    "Enterprise Admins" : {
        "path" : "CN=Users,DC=haas,DC=local",
        "members" : [
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
    "Schema Admins" : {
        "path" : "CN=Users,DC=haas,DC=local",
        "members" : [
        ],
        "foreign_users": [],
        "foreign_gmsas": [],
        "foreign_computers": [],
        "foreign_groups": []
    },
}