plbr_hostname: "bastion"

wabadmin_user: wabadmin
# old: SecureWabAdmin
wabadmin_password: Wab*Admin*Secure1
wabsuper_user: wabsuper
wabsuper_password: Wab*Super*Secure1
wabbootadmin_user: wabbootadmin
wabbootadmin_password: Wab*Super*Secure1
wabupgrade_user: wabupgrade
wabupgrade_password: Wab*Upgrade*Secure1

crypt_key: Zaebuj12345+-Zaebuj12345+-

# hostname: wawa
# ip: 172.17.2.30

plbr_api_user: "admin"
plbr_api_password: "Zaebuj12345+-"
plbr_api_key: {
  user: 'admin',
  key: "8QlOMR0nr53XRVKjSEU2DtjapEmAmBPCYrVLgtpZHfM"
}

#bastion_url: "https://{{ ansible_host }}/api"
bastion_url: "https://{{ plbr_domain_ip }}/api"
ansible_user: "root"
ansible_ssh_private_key_file: ~/.ssh/id_wallix
#ansible_user: "{{ wabadmin_user }}"
#ansible_password: "{{ wabadmin_password }}"
#ansible_become_pass: "{{ wabadmin_password }}"
ansible_connection: ssh
ansible_port: 2242


device_account_json: >
  {
    "account_name": "IN_DEVICE_ACCOUNT_NAME",
    "account_login": "IN_DEVICE_ACCOUNT_LOGIN",
    "description": "IN_DEVICE_ACCOUNT_NAME",
    "credentials": [
        {
            "type": "password",
            "password": "IN_DEVICE_ACCOUNT_PASSWORD"
        }
    ],
    "checkout_policy": "default"
  }

plbr_users: {
  "zaebuj": {
    email: "zaebuj@haas.local",
    ip_source: "10.0.0.1",
    preferred_language: "en",
    profile: "product_administrator",
    is_disabled: false,
    user_auths: ["local_password", "local_sshkey"], # local_password, local_sshkey, local_x509
    password: "Jubeaz12345+-",
    force_change_pwd: "true",
    ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDRnX471jdDOC1BoaQwJa9Uzkf9xOHkfdTbu0xPRSUiyMxE3eLzJBo5vnjT8Hoc+GbP2I9qCC4B43tjNcoby8Fy4jMTKKit0MWCzvUmTPJhKh7QlB6tLh3MGEG7zDrCVlgaH1041Oyp21ZgiCjkqQl/ClTS5vplgyG4ZlFy/lnFrVULr20D1smo9Ihbhol0glkOpiY6+NBSTIScIgtLx7Fo1YS5wQ0pPHIFttbbLQgvEF2NCOpJ6SZTG9/gZp4Uo4sgGJFzxIent/28E7QZXsCeF8SQ+Bq8K4R0v3VMihcZgkFwcr6wmUc9A8/LG1kaD67A+Nrt1X2Jl1BhO41qGJtZ1PNuYxZaBLOuAnP3GiDZ7wFjkPml8BdrACHgCqa8hKB0FuRllfFNSQb9hTTAJtslskKlZKtfV4BahVe6Ceb9r8UHhQRYtZok3iPhpCK09BZbTWv0IQra5QQm/kj0rtUT78kwP4oYcsR+iV3/U9S+QIFgATSucZ4edzP37itcqsX+CP4cZfJNKzSBHIXNlfhSH48egD8svbEeNl2NyKLP8TcMgU+IPW5gqpf999YfhLIEvklxM9RTUkeCrNPb6wzlmMs9YGh7kXvci1UK+dYa/GdLuffyV1YW9xtuASL08DOd8u02+VwwpNVgUUsBmx1mUBQ4/coa5vYoFDJlZMHqPw== jubeaz@somewhere",
    gpg_public_key: "",
    certificate_dn: ""
  },
  "jubeaz": {
    email: "jubeaz@haas.local",
    ip_source: "",
    preferred_language: "en",
    profile: "user",
    is_disabled: false,
    user_auths: ["local_password"], # local_password, local_sshkey, local_x509
    password: "Zaebuj12345+-",
    force_change_pwd: "false",
    ssh_public_key: "",
    gpg_public_key: "",
    certificate_dn: ""
  }
}


plbr_usergroups: {
  "product_adm": {
    description: "product_administrator",
    timeframes: ["allthetime"],
    users: ["zaebuj"],
    profile: "product_administrator",
    language: "en",
    email_list: "",
    restrictions: []
  },
  "lab_local_adm": {
    description: "Access to local admin accounts",
    timeframes: ["allthetime"],
    users: ["jubeaz"],
    profile: "user",
    language: "en",
    email_list: "",
    restrictions: [
      {action: "kill", rules: 'sudo\\s+.*', subprotocol: "SSH_SHELL_SESSION"},
    ]
  },
  "lab_Domain_Admin": {
    description: "Access with Domain Admin",
    timeframes: ["allthetime"],
    users: ["jubeaz"],
    profile: "user",
    language: "en",
    email_list: "",
    restrictions: [
      {action: "kill", rules: 'sudo\\s+.*', subprotocol: "SSH_SHELL_SESSION"},
    ]
  }
}

plbr_domain_dc_inventory_key: "dc_haas"
plbr_bastion_directory: ""
plbr_external_authentication_domain_account: "lowpriv"


plbr_connection_policy_rdp_session: {
    inactivity_timeout: 0
}

plbr_connection_policy_rdp_rdp: {
    enable_nla: true,
    enable_kerberos: true,
    allow_nla_ntlm_fallback: false,
    allow_tls_only_fallback: false,
    server_redirection: false,
    load_balance_info: "",
    use_client_provided_alternate_shell: false,
    use_client_provided_remoteapp: false,
    use_native_remoteapp_capability: true,
    wabam_uses_translated_remoteapp: false,
    enable_remotefx:  false,
    enable_restricted_admin_mode:  false,
    force_smartcard_authentication:  false,
    enable_ipv6: true,
    mode_console: "allow",
    bogus_monitor_layout_treatment: false,
    use_session_probe_to_launch_remote_program: true
}

plbr_connection_policy_rdp_ssession_probe: {
    enable_session_probe: true,
    use_smart_launcher: true,
    on_launch_failure: "1",
    start_launch_timeout_timer_only_after_logon: true,
    on_keepalive_timeout: "2",
    end_disconnected_session: false,
    enable_autodeployed_appdriver_affinity: true,
    extra_system_processes: "",
    windows_of_these_applications_as_unidentified_input_field: "",
    enable_bestsafe_interaction: false,
    on_account_manipulation: "0",
    public_session: false,
    outbound_connection_monitoring_rules: "",
    process_monitoring_rules: ""
}

plbr_connection_policy_rdp_server_cert: {
  server_cert_store: true,
  server_cert_check: "3"
}

plbr_connection_policy_rdp_session_log: {
  keyboard_input_masking_level: "2"
}

 
plbr_connection_policy_rdp_file_verification: {
  enable_up: false,
  enable_down: false,
  clipboard_text_up: false,
  clipboard_text_down: false,
  block_invalid_file_up: false,
  block_invalid_file_down: false
}

plbr_connection_policy_rdp_file_storage: {
  store_file: "never"
}