plbr_local_users: {
    "LA_jubeaz" : {
        "password"        : "Zaebuj12345+-", 
        }
}

plbr_local_groups: {
    "Administrators" : [".\\LA_jubeaz", "research.haas.local\\L_LOCAL_ADMINS", "research.haas.local\\L_LOCAL_ADMINS_FENRIS"],
    "Remote Management Users": [".\\LA_jubeaz","research.haas.local\\L_LOCAL_ADMINS", "research.haas.local\\L_LOCAL_ADMINS_FENRIS", "research.haas.local\\lowpriv"],
    "Remote Desktop Users" : [".\\LA_jubeaz","research.haas.local\\L_LOCAL_ADMINS", "research.haas.local\\L_LOCAL_ADMINS_FENRIS", "research.haas.local\\lowpriv"],
}