domain_ous: {
    "Titan"           : { "name": "Titan",          "path" : "DC=research,DC=weyland,DC=local"},
    "Skorpios"        : { "name": "Skorpios",       "path" : "DC=research,DC=weyland,DC=local"},
    "Black Ops"       : { "name": "Black Ops",      "path" : "OU=Titan,DC=research,DC=weyland,DC=local"},
    "BO_servers"      : { "name": "Servers",        "path" : "OU=Black Ops,OU=Titan,DC=research,DC=weyland,DC=local"},
    "BO_workstations" : { "name": "Workstations",   "path" : "OU=Black Ops,OU=Titan,DC=research,DC=weyland,DC=local"},
    "BO_services"     : { "name": "Services",       "path" : "OU=Black Ops,OU=Titan,DC=research,DC=weyland,DC=local"},
    "BO_groups"       : { "name": "Groups",         "path" : "OU=Black Ops,OU=Titan,DC=research,DC=weyland,DC=local"},
    "BO_users"        : { "name": "Users",          "path" : "OU=Black Ops,OU=Titan,DC=research,DC=weyland,DC=local"},
    "BO_admins"       : { "name": "Admins",         "path" : "OU=Black Ops,OU=Titan,DC=research,DC=weyland,DC=local"},
    "Grey Ops"        : { "name": "Grey Ops",       "path" : "OU=Titan,DC=research,DC=weyland,DC=local"},
    "GO_servers"      : { "name": "Servers",        "path" : "OU=Grey Ops,OU=Titan,DC=research,DC=weyland,DC=local"},
    "GO_workstations" : { "name": "Workstations",   "path" : "OU=Grey Ops,OU=Titan,DC=research,DC=weyland,DC=local"},
    "GO_services"     : { "name": "Services",       "path" : "OU=Grey Ops,OU=Titan,DC=research,DC=weyland,DC=local"},
    "GO_groups"       : { "name": "Groups",         "path" : "OU=Grey Ops,OU=Titan,DC=research,DC=weyland,DC=local"},
    "GO_users"        : { "name": "Users",          "path" : "OU=Grey Ops,OU=Titan,DC=research,DC=weyland,DC=local"},
    "GO_admins"       : { "name": "Admins",         "path" : "OU=Grey Ops,OU=Titan,DC=research,DC=weyland,DC=local"},
    "White Ops"       : { "name": "White Ops",      "path" : "OU=Titan,DC=research,DC=weyland,DC=local"},
    "WO_servers"      : { "name": "Servers",        "path" : "OU=White Ops,OU=Titan,DC=research,DC=weyland,DC=local"},
    "WO_workstations" : { "name": "Workstations",   "path" : "OU=White Ops,OU=Titan,DC=research,DC=weyland,DC=local"},
    "WO_services"     : { "name": "Services",       "path" : "OU=White Ops,OU=Titan,DC=research,DC=weyland,DC=local"},
    "WO_groups"       : { "name": "Groups",         "path" : "OU=White Ops,OU=Titan,DC=research,DC=weyland,DC=local"},
    "WO_users"        : { "name": "Users",          "path" : "OU=White Ops,OU=Titan,DC=research,DC=weyland,DC=local"},
    "WO_admins"       : { "name": "Admins",         "path" : "OU=White Ops,OU=Titan,DC=research,DC=weyland,DC=local"},
    "IT"              : { "name": "IT",             "path" : "OU=Titan,DC=research,DC=weyland,DC=local"},
    "IT_servers"      : { "name": "Servers",        "path" : "OU=IT,OU=Titan,DC=research,DC=weyland,DC=local"},
    "IT_workstations" : { "name": "Workstations",   "path" : "OU=IT,OU=Titan,DC=research,DC=weyland,DC=local"},
    "IT_services"     : { "name": "Services",       "path" : "OU=IT,OU=Titan,DC=research,DC=weyland,DC=local"},
    "IT_groups"       : { "name": "Groups",         "path" : "OU=IT,OU=Titan,DC=research,DC=weyland,DC=local"},
    "IT_users"        : { "name": "Users",          "path" : "OU=IT,OU=Titan,DC=research,DC=weyland,DC=local"},
    "IT_admins"       : { "name": "Admins",         "path" : "OU=IT,OU=Titan,DC=research,DC=weyland,DC=local"}
}