local_admin_password: "Jubeaz12345+-"
windows_update: false 

local_users: {
#    "arose" : {
#        "password"        : "z77w_TeCUCD_wLrD", 
#        "groups"          : ["Remote Management Users", "Administrators"]
#        }
}

local_groups: {
    "Administrators" : [],
    "Remote Desktop Users" : [],
    "Remote Management Users": []
}


#scripts: ["sidhistory.ps1"]
#vulns: ["disable_firewall"]

# server: https://learn.microsoft.com/en-us/windows-server/administration/server-core/server-core-roles-and-services
# worksation: Get-WindowsCapability -Name RSAT* -Online |
extra_features: []
#softwares: [  "git", "visualstudio2022community", "notepadplusplus"]
#
#user_repos: {
#    jubeaz: [
#        ["Mimikatz", "https://github.com/gentilkiwi/mimikatz.git"],
#        ["Rubeus", "https://github.com/GhostPack/Rubeus"]
#    ]
#}
#user_downloads: {
#    jubeaz: [
#        ["GRMWDK_EN_7600_1.ISO", "https://download.microsoft.com/download/4/A/2/4A25C7D5-EFBE-4182-B6A9-AE6850409A78/GRMWDK_EN_7600_1.ISO"]
#    ]
#}

