# 0: UAC won't prompt (like disabled)                                                                                                                                                                  │
# 1: ask for username and password to execute the binary with high rights (on Secure Desktop)                                                                                                          │
# 2: Always notify me ask for confirmation to the administrator when he tries to execute something with high privileges (on Secure Desktop)                                                            │
# 3: like 1 but not necessary on Secure Desktop                                                                                                                                                        │
# 4: like 2 but not necessary on Secure Desktop                                                                                                                                                        │
# 5: ask the administrator to confirm to run non Windows binaries with high privileges     
#uac_status_level: 5
#enable_run_as_ppl: false,
#windows_defender: true

connection_profiles: {
#  #"domain":  {"interface": "{{domain_adapter}}", "NetworkCategory": "Public", "IPv4Connectivity": "", "IPv6Connectivity": ""}
#  "public":  {"interface": "{{pub_adapter}}",     "NetworkCategory": "Public", "IPv4Connectivity": "LocalNetwork", "IPv6Connectivity": "Disconnected"}
}

firewall_profiles: {
#  "Domain": {"status": "enabled", "inbound": "allow", "outbound": "allow"},
#  "Public": {"status": "enabled", "inbound": "allow", "outbound": "allow"},
#  "Private": {"status": "enabled", "inbound": "allow", "outbound": "allow"},
#  # enabled, disabled, # ["Domain", "Private", "Public"], # "allow", "block", "not_configured",  # "allow", "block", "not_configured"
}

firewall_rules: {
#   "FTP_IN_1": {
#      "name": "FTP In",
#      "enabled": true, 
#      "action": "allow", 
#      "profiles": ["Domain"], 
#      "direction": "inbound", # inbound, outbound
#      "localip": ["any"], 
#      "localport": [21],  
#      "protocol": "tcp", # any or value
#      "remoteip": ["any"],  
#      "remoteport": ["any"] 
#      #"group": "ansible" # default ansible
#    }
}

