---
- name: ENSURE DOMAINS ARE REACHABLE
  import_playbook: books/domains-reachable.yml

# ##################################
# Start Extended inventory computing
# ##################################
- name: COMPUTE EXTENDED INVENTORY (LOCAL)
  import_playbook: books/compute-properties_local.yml

- name: COMPUTE EXTENDED INVENTORY (DOMAIN)
  import_playbook: books/compute-properties_domain.yml

- name: COMPUTE EXTENDED INVENTORY (FOREST)
  import_playbook: books/compute-properties_forest.yml
  when: groups["child_dc"] | length > 0

- name: COMPUTE EXTENDED INVENTORY (TRUST)
  import_playbook: books/compute-properties_trust.yml
  when: groups["trust"] | length > 0

- name: COMPUTE EXTENDED INVENTORY (MSSQL)
  import_playbook: books/compute-properties_mssql.yml
  when: groups["mssql"] | length > 0
# ################################
# End Extended inventory computing
# ################################

- name: COMPUTER COMPLIANCE SETUP
  import_playbook: books/computers-build.yml

- name: BUILD FORESTS
  import_playbook: books/domain-build.yml

- name: DOMAINS ORGANIZATIONAL UNITS
  import_playbook: books/domain-ous.yml

- name: MEMBER JOIN
  import_playbook: books/members-join.yml

- name: TRUST BUILD
  import_playbook: books/trust-build.yml

- name: LAPS SETUP
  import_playbook: books/domain-laps-setup.yml

- name: MEMBER ADCS
  import_playbook: books/domain-adcs_build.yml

- name: DOMAIN DATA
  import_playbook: books/domain-data.yml

- name: DOMAIN ACLS
  import_playbook: books/domain-acl.yml

# - name: Compute extended inventory
#   import_playbook: books/compute-global-mappings.yml

- name: MEMBER DOMAIN SETUP
  import_playbook: books/members-domain-setup.yml

- name: COMPUTER LOCAL GROUPS / USERS ...
  import_playbook: books/computers-local-groups-users-rights.yml

- name: COMPUTER SECURITY
  import_playbook: books/computers-security.yml

- name: MEMBER IIS
  import_playbook: books/members-iis.yml

- name: MEMBER WEBDAV
  import_playbook: books/members-webdav.yml

- name: MEMBER MSSQL
  import_playbook: books/members-mssql.yml

- name: MEMBER USER DATA
  import_playbook: books/members-user_data.yml
