---

- name: Ensure domains are reachable
  import_playbook: books/domains-reachable.yml

# ##################################
# Start Extended inventory computing
# ##################################
- name: COMPUTE EXTENDED INVENTORY (LOCAL)
  import_playbook: books/compute-properties_local.yml

- name: COMPUTE EXTENDED INVENTORY (DOMAIN)
  import_playbook: books/compute-properties_domain.yml

- name: COMPUTE EXTENDED INVENTORY (FOREST)
  import_playbook: books/compute-properties_forest.yml
  when: groups["child_dc"] | length > 0

- name: COMPUTE EXTENDED INVENTORY (TRUST)
  import_playbook: books/compute-properties_trust.yml
  when: groups["trust"] | length > 0

- name: COMPUTE EXTENDED INVENTORY (MSSQL)
  import_playbook: books/compute-properties_mssql.yml
  when: groups["mssql"] | length > 0

- name: COMPUTE EXTENDED INVENTORY (EXCHANGE)
  import_playbook: books/compute-properties_exchange.yml
# ################################
# End Extended inventory computing
# ################################

- name: DEPLOY EXCHANGE
  import_playbook: books/members-exchange.yml
